### DISCUSSION TITLE
Add boolean option to `calendar.get_events` to merge output

### DISCUSSION THREAD

**Discussion by KayOhtie** [home-assistant/architecture#1045] [Entity Models] [answered]
Goals:

 * Simplify the ability to iterate through all events for a set of calendars in templates
 * Reduce confusion for new users utilizing `calendar.get_events`
 * Improve reliability for blueprints or other cases where calendars used may vary per execution

I really love the new service calls model for allowing responses. This is great for getting information back from entities that don't directly expose them as an attribute, and makes it even easier to fetch this information from ones that do!

The `calendar.get_events` service call is great for being able to select from multiple. However, I ran into the same level of confusion as several others have on the forums repeatedly with regards to the response from the call, and how to utilize it.

From a programmatic (or even declarative) standpoint, the data structure returned is unusual. A `list` of entries (calendar entity IDs) is fed in, and one could reasonably expect one of two outputs: a `list` of calendar objects, each containing `entity_id` and `events` attributes/fields for events within the range, or a `list` of all events that fall within the selected range for all calendars supplied, merged together.

The example used in documentation shows explicitly requesting two calendars and then using each's output separately. I believe that while that is a completely valid use case, and given being established already should likely remain the default, it's the least likely use case of the output. Most of the time, when I want to hear or read my agenda, I don't want it separated by type of entry. I want them all in chronological order, because it gives a sense of when work or play or other activities occur to help me plan around them, and I believe this is the case for most people.

What I'm proposing is a boolean option that can be supplied to the `calendar.get_events` call to return the events 'collated', effectively, in chronological order. Jinja2's limitations make iterating over the current output quite difficult, requiring nested `for` loops, whereas a list of entries would allow easily listing them all chronologically.

I'm currently doing this using a macro in jinja:

```jinja2
{% macro collapse_calendars(calendars) -%}
{% set agenda = namespace(x=[]) -%}
{% for calendar_id, calendar_object in calendars|dictsort -%}
  {% for event in calendar_object.events -%}
    {% set agenda.x = agenda.x + [event] %}
  {%- endfor %}
{%- endfor %}
{{- agenda.x|sort(attribute='start')|to_json }}
{%- endmacro %}
```

This doesn't preserve types however, requiring conversion again on dates to format as a string. In addition, it's a considerable amount of boilerplate if not using a macro, and even with a macro it's 2 lines of unnecessary boilerplate (the import and the set `from_json` ) to get a list of entries that I feel should be an option for output if not a default.

My proposed structure for output in YAML would be more like this:

```yaml
- summary: Recital
  detail: Piano recital at school
  start: '2024-02-26T18:00:00-06:00'
  end: '2024-02-26T21:00:00-06:00'
  calendar_entity_id: calendar.school_calendar
```

I know it's difficult to satisfy everyone's use cases. This seems like a case where both routes are valid, especially the full list, and it'd be a breaking change for existing users. I don't know if a boolean to a new data structure or if something else entirely is the better outcome here, but it does seem to create a level of complication as-is, whereas implementing the same example given when using a list of all entries with a `calendar_entity_id` field of some type would be much more trivial than merging and sorting:

```jinja2
service: notify.nina
data:
  title: Daily agenda for {{ now().date() }}
  message: >-
    Your school calendar for today:
    {% for event in agenda|selectattr("calendar_entity_id","equalto","calendar.school_calendar") %}
    {{ event.start}}: {{ event.summary }}<br>
    {% endfor %}
    Your work calendar for today:
    {% for event in agenda|selectattr("calendar_entity_id","equalto","calendar.work_calendar")%}
    {{ event.start}}: {{ event.summary }}<br>
    {% endfor %}
```

The only change from the example to the new structure would be changing `["calendar.school_calendar"]["events"]` to `|selectattr("calendar_entity_id","equalto","calendar.school_calendar")` to filter events.

I feel like a list of events as output is more welcoming to newcomers, and more fitting for the way this information would typically be displayed, with an easy means of filtering in the same way it already does.

**Comment by emontnemery** [comment]
@Ceralor Could you add examples of the output of the service, both as it is today, and with your proposed change, for the problematic case, i.e. events from multiple calendars?

**Reply by KayOhtie** [reply]
Added as an additional comment on the discussion since my original message was really long already. I also included a screenshot to help reinforce the considerations.

**Comment by KayOhtie** [comment]
For an example directly them, I did a few examples for a call. The request:

```yaml
service: calendar.get_events
target:
  entity_id:
    - calendar.local_furry_events
    - calendar.personal
    - calendar.sports
    - calendar.yap_house_schedules
data:
  end_date_time: "2024-02-26 23:59:00"
  start_date_time: "2024-02-26 00:00:00"
```

Currently, the output looks as follows:

```yaml
calendar.sports:
  events:
    - start: "2024-02-26T17:00:00-06:00"
      end: "2024-02-26T18:00:00-06:00"
      summary: Basketball vs. Rockets
      description: ""
calendar.local_furry_events:
  events: []
calendar.yap_house_schedules:
  events:
    - start: "2024-02-26T08:00:00-06:00"
      end: "2024-02-26T09:00:00-06:00"
      summary: Dr. Appt
      description: ""
    - start: "2024-02-26T20:00:00-06:00"
      end: "2024-02-26T21:00:00-06:00"
      summary: Bake a cake
      description: something good
calendar.personal:
  events: []
```

My proposal would look like this:

```yaml
- start: "2024-02-26T08:00:00-06:00"
  end: "2024-02-26T09:00:00-06:00"
  summary: Dr. Appt
  description: ""
  entity_id: calendar.yap_house_schedules
- start: "2024-02-26T17:00:00-06:00"
  end: "2024-02-26T18:00:00-06:00"
  summary: Basketball vs. Rockets
  description: ""
  entity_id: calendar.sports
- start: "2024-02-26T20:00:00-06:00"
  end: "2024-02-26T21:00:00-06:00"
  summary: Bake a cake
  description: something good
  entity_id: calendar.yap_house_schedules
```

Note that despite being from different calendars, the events are in chronological order, merged together as a single list of event objects. Since `calendar.get_events` already exists with expected output of object:object:list shape, a boolean alone may be the wrong step, and instead a new call `calendar.get_events_merged` or similar naming? I'm uncertain, but I do think this would be incredibly valuable. Listing multiple calendars merged is also consistent with the default Calendars card.

![Screenshot 2024-02-26 160456](https://github.com/home-assistant/architecture/assets/615460/6671a075-bd47-4aa4-89ce-e0afc4dae095)

These are listed chronologically, and I do not understand why the service call breaks what one might reasonably expect for output based on that card, and feel that there should either be:

 - Change to existing `calendar.get_events` output (Breaking Change)
 - Addition of 'merge' boolean to `calendar.get_events` for alternate output (Non-breaking, but different data structure)
 - New service call returning a list of events (Non-breaking but additional upkeep)
