### DISCUSSION TITLE
Allow templates for enabling automation triggers, conditions and actions

### DISCUSSION THREAD

**Discussion by farmio** [home-assistant/architecture#1066] [General] [answered]
Currently an automation trigger can be disabled by setting `enabled` to `false`.
https://www.home-assistant.io/docs/automation/trigger/#disabling-a-trigger
So can conditions and actions, although it is not documented for yaml (but it is what happens when "Disable" / "Enable" is used in the automation editor).

```yaml
automation:
  trigger:
    - enabled: false
      platform: ...
```
Allowed values are booleans, numbers and strings ("on", "off", "true", "false", etc.)  https://github.com/home-assistant/core/blob/5aabb2a920ab3810e6fcdec4de4e8698b22a960f/homeassistant/helpers/config_validation.py#L1651

For Blueprints, it would be nice to be able to disable a specific items based on an input (or its default value if nothing is set by the user).
```yaml
blueprint:
  name: Dependent disable
  domain: automation
  input:
    required_input:
      name: Required
    optional_input:
      name: Optional
      default: false
    binary_input:
      name: Use action
      selector:
        boolean:

trigger_variables:
  _optional_input: !input optional_input

trigger:
  - platform: mqtt
    topic: !input required_input
  - platform: mqtt
    topic: !input optional_input
    enabled: "{{ not _optional_input == False }}"
    # or maybe even simpler without trigger_variable
    enabled: !input optional_input

action:
  - service: system_log.write
    enabled: !binary_input
    data:
      level: info
      message: "{{ trigger }}"
```

To achieve this, the `enabled` key would have to allow limited templates
```py
vol.Optional(CONF_ENABLED): vol.Any(boolean, template),
```
and evaluate these in `async_initialize_triggers()` https://github.com/home-assistant/core/blob/65230908c6bd7b9f2dac6e8de41b7bd27d28d1be/homeassistant/helpers/trigger.py#L313

and according methods for condition and action.

While, for conditions and actions, we could support full templates, `enabled` is still restricted to limited templates. This fits for the intended use case of templating based on blueprint inputs. For other needs, users can already use `and` in conditions or `if` in actions that provide full templates.

PR for implementations: 
- trigger: https://github.com/home-assistant/core/pull/114458
- condition: https://github.com/home-assistant/core/pull/117047
- action: https://github.com/home-assistant/core/pull/117049
