### DISCUSSION TITLE
Unit conversion causes self-referencing sensors to break

### DISCUSSION THREAD

**Discussion by mekaneck** [home-assistant/architecture#1075] [Entity Models]
Let's define a trigger-based template sensor which reports the max temperature from all time:
```yaml
template:
  - trigger:
      - platform: state
        entity_id: sensor.outside_temperature_celsius
    sensor:
      - name: "Max Outside Temperature"
        unit_of_measurement: "°C"
        device_class: temperature
        state: "{{ max(this.state | float(0), trigger.to_state.state | float(0) }}"
```

If this template sensor stays in °C, there is no issue. However if the units are changed to °F from the UI, we now have a scenario where the undesired value is selected by the `max` function (because `this.state` has already been converted to °F and is therefore larger). Even worse, that returned value is again "converted" to °F. The end result is that upon each trigger, the value of this template sensor skyrockets due to double-conversion.

This unintended behavior will occur for any sensor which:
- is defined with a device_class that supports unit conversions
- contains a template which self-references
- has its unit of measurement changed, either by a user from the UI or automatically by HA due to the unit system selected when the sensor was added.
