### DISCUSSION TITLE
Expose media_player.async_browse_media as a service

### DISCUSSION THREAD

**Discussion by PeteRager** [home-assistant/architecture#1079] [Entity Models] [answered]
The topic of this discussion is to consider extending the entity model to expose the existing media_player.async_browse_media method as a service call.  This method call is currently exists and is used by the media browser through a websocket interface.

The change is to expose this as a service call with a return value,  There is a draft pr here:
https://github.com/home-assistant/core/pull/116452

The purpose is to allow automations to access the service to browse for media (just as you can do from the UI) and then use the return values to do other actions. As an example, here is an automation that gets a list of the albums by the Beatles and randomly plays one.  This is using a Sonos music library.

```
alias: play_beatles
description: ""
trigger: []
condition: []
action:
  - service: media_player.browse_media
    metadata: {}
    data:
      media_content_id: A:ALBUMARTIST/Beatles
      media_content_type: album
    response_variable: albums
    target:
      entity_id: media_player.master_bedroom_2
  - variables:
      num_children: "{{ albums['media_player.master_bedroom_2']['children'] | length }}"
      random_album_index: "{{ range(1, num_children - 1) | random }}"
      random_album_media_id: >-
        {{
        albums['media_player.master_bedroom_2']['children'][random_album_index]['media_content_id']
        }}
  - service: media_player.play_media
    target:
      entity_id: media_player.master_bedroom_2
    data:
      media_content_id: "{{ random_album_media_id }}"
      media_content_type: album
    metadata: {}
mode: single
```

Here is a sample of the YAML returned when running the browse_media service from developer tools / services

```
media_player.master_bedroom_2:
  title: Beatles
  media_class: album
  media_content_type: album
  media_content_id: A:ALBUMARTIST/Beatles
  children_media_class: directory
  can_play: false
  can_expand: false
  thumbnail: null
  not_shown: 0
  children:
    - title: All
      media_class: artist
      media_content_type: artist
      media_content_id: A:ALBUMARTIST/Beatles/
      children_media_class: null
      can_play: true
      can_expand: true
      thumbnail: null
    - title: A Hard Day's Night
      media_class: album
      media_content_type: album
      media_content_id: A:ALBUMARTIST/Beatles/A%20Hard%20Day's%20Night
      children_media_class: null
      can_play: true
      can_expand: true
      thumbnail: >-
        http://192.168.50.40:1400/getaa?u=x-file-cifs://192.168.50.70/music/iTunes/iTunes%20Media/Music/The%20Beatles/A%20Hard%20Day's%20Night/01%20A%20Hard%20Day's%20Night%201.m4a&v=53
    - title: Abbey Road
      media_class: album
      media_content_type: album
      media_content_id: A:ALBUMARTIST/Beatles/Abbey%20Road
      children_media_class: null
      can_play: true
      can_expand: true
      thumbnail: >-
        http://192.168.50.40:1400/getaa?u=x-file-cifs://192.168.50.70/music/iTunes%20Music/The%20Beatles/Abbey%20Road/01%20Come%20Together.mp3&v=53
```
