### DISCUSSION TITLE
Drop the use of .coveragerc

### DISCUSSION THREAD

**Discussion by frenck** [home-assistant/architecture#1105] [General] [answered]
A proposal to change how we monitor and report the test coverage of our codebase.

## Current State

Currently, our project's code test coverage is reported to be around 97%. However, this high percentage is artificially maintained by excluding files that do not meet our coverage threshold using the `.coveragerc` file.

## Objective

The primary goal of this proposal is to obtain a more accurate insight into our actual test coverage and identify areas for improvement.

## Proposal

I propose to stop excluding files from test coverage reports for all integrations. By doing so, coverage tools like CodeCov will provide a more accurate representation of our coverage gaps. This change will:

- Enhance the value of coverage tools by providing better visibility into coverage gaps.
- Eliminate the need to maintain coverage exclusions.
- Simplify our process by removing the need to explain the reasons behind these exclusions constantly.

## Impact

Accepting this proposal will result in a significant drop in reported test coverage. However, CodeCov will continue to ensure 100% coverage for essential files (e.g., configuration flows), as it currently does.

For reference the current configuration at the time of writing:

```yaml
coverage:
  status:
    project:
      default:
        target: 90
        threshold: 0.09
      required:
        target: auto
        threshold: 1
        paths:
          - homeassistant/components/*/config_flow.py
          - homeassistant/components/*/device_action.py
          - homeassistant/components/*/device_condition.py
          - homeassistant/components/*/device_trigger.py
          - homeassistant/components/*/diagnostics.py
          - homeassistant/components/*/group.py
          - homeassistant/components/*/intent.py
          - homeassistant/components/*/logbook.py
          - homeassistant/components/*/media_source.py
          - homeassistant/components/*/recorder.py
          - homeassistant/components/*/scene.py
```

## Implementation plan

Implementing the suggested changes requires two changes:

1. Remove `.coveragerc` file (get rid of all exclusions)
2. Move coverage "general" settings into `pyproject.toml`
3. Adjust the `codecov.yml` file, removing the default project target (and letting it automatically handle it based on a threshold) and adding a target for the required threshold.
4. Remove coveragerc references from the developer documentation.

The Codecov default project threshold might need to be re-evaluated afterward.
 
## Optional future enhancements

- Instate the `python-coverage-comment-action` in our CI pipelines.
  <https://github.com/py-cov-action/python-coverage-comment-action>
  Example: <https://github.com/py-cov-action/python-coverage-comment-action-v3-example/pull/1#issuecomment-1244424488>
- "Coverage goals"
  <https://nedbatchelder.com/blog/202111/coverage_goals.html>

## Changelog

**4 July, 2024, 15:24 CEST**: Adjusted the proposal to remove all coverage exclusions (instead of only integrations/components).
