### DISCUSSION TITLE
Ask Question on Assist Satellite device

### DISCUSSION THREAD

**Discussion by balloob** [home-assistant/architecture#1150] [Entity Models] [answered]
This extracts https://github.com/home-assistant/architecture/discussions/1143#discussioncomment-10757780 into it's own proposal. It is meant to work with the built-in Home Assistant conversation agent. 

## Context

With the introduction of Assist Satellite entities, we now have a representation of devices that allow users to talk with Assist. Some of these devices are also able to _start_ a conversation with a user without the user initiating the conversation via a wake-word or button press.

The Home Assistant built-in conversation agent works with sentence matching. This makes it hard to extend it and continue a conversation.

## Proposal

_draft implementation @ https://github.com/home-assistant/core/pull/145233_

Introduce a new Assist Satellite service `ask_question` to allow Home Assistant to announce a message on an Assist Satellite device and capture the response from the user. The service is guarded by the existing `START_CONVERSATION` supported feature. The answer is sent through STT and the answer is extracted per info passed into the `ask_question` action and returned as the service response value.

Use cases:
- Ask user what music they want to listen to, sent the response to search of a media player

```yaml
actions: 
  - action: assist_satellite.ask_question
    data:
      entity_id: assist_satellite.living_room_voice_assistant
      preannounce: true   # optional
      preannounce_media_id: media-source://...   # optional
      question: What kind of music do you want to listen to?
      answers:
        - id: genre
          sentences:
            - "genre {genre}"
        - id: artist
          sentences:
            - "artist {artist}"


    response_variable: answer
  - choose:
      - conditions: '{{ answer.id == "genre" }}'
        sequence:
          - action: music_assistant.play_media
            data:
              media_id: "My {{ answer.slots.genre }} playlist"
              media_type: playlist
            target:
              entity_id: media_player.living_room_speakers
      - conditions: '{{ answer.id == "artist" }}'
        sequence:
          - action: music_assistant.play_media
            data:
              media_id: "{{ answer.slots.artist }}"
              media_type: artist
            target:
              entity_id: media_player.living_room_speakers
```

```yaml
# Response variable (scoped under entity_id in an action)
answer:
  id: genre
  sentence: I want to listen to some jazz
  slots:
    genre: jazz
```

```yaml
actions: 
  - action: assist_satellite.ask_question
    data:
      entity_id: assist_satellite.living_room_voice_assistant
      preannounce: true   # optional
      preannounce_media_id: media-source://...   # optional
      question: What kind of music do you want to listen to?
      answers:
        - sentences:
            - "genre {genre}"
          actions:
          - action: music_assistant.play_media
            data:
              media_id: "My {{ answer.slots.genre }} playlist"
              media_type: playlist
            target:
              entity_id: media_player.living_room_speakers

        - sentences:
            - "artist {artist}"
          actions:
          - action: music_assistant.play_media
            data:
              media_id: "{{ answer.slots.artist }}"
              media_type: artist
            target:
              entity_id: media_player.living_room_speakers
```

## Alternative

Add `answers` to `start_conversation`. This would be confusing because then `answers` would work for non-LLMs, while `extra_system_prompt` would be an LLM specific option. Keeping them separate allows for growing both services in the future.
