### DISCUSSION TITLE
`climate` entity: Make min/max setpoints optional, do not validate using assumed setpoint ranges

### DISCUSSION THREAD

**Discussion by AlCalzone** [home-assistant/architecture#1152] [Entity Models]
_I'll use thermostats as an example, but the principle applies to all setpoint types of climate devices._

## Background

When changing setpoints of thermostats, recent releases (I'm not clear which PR did it) validate that the new setpoint lies between the min and max, and don't accept any setpoints outside of this range. For some devices however, it is not possible to determine the range of valid setpoints, so the defaults of 7...35°C are chosen, preventing users from setting valid setpoints outside of this range.

Some examples are Z-Wave devices which implement `Thermostat Setpoint CC` version 1 or 2, which are still pretty common.

This has been reported in https://github.com/home-assistant/core/issues/123612

While validating setpoints sounds reasonable, enforcing them when the range of valid values is **assumed** seems wrong however. In addition, this violates a Z-Wave certification requirement:
![grafik](https://github.com/user-attachments/assets/4936c03d-cf19-4cd8-b8f7-5ba631951643)

_Yes, I'm aware that HA does not model its entities after a single protocol, but in this case the Z-Wave requirements follow common sense in my opinion: When the range is not known, leave the choice to the user._

## Proposal

- Make `min_temp`, `min_humidity`, `max_temp` and `max_humidity` optional.
- Do not enforce that the `setpoint >= min` when `min` is unknown
- Do not enforce that the `setpoint <= max` when `max` is unknown.
- Where both limits are required, e.g. for display purposes in the UI, keep assuming the default values for the missing properties, as long as this does not lead to an invalid range, e.g. when `max_temp < DEFAULT_MIN_TEMP`.

**Comment by EnochPrime** [comment]
I think I found where this was introduced.
https://github.com/home-assistant/core/pull/118649

**Comment by PeteRager** [comment]
I like the approach as it gets us out of the current issue and the work for each integration is minimal or none if it's defaulting to the base class implementation.

Two notes.

a) Right now the UI limits may be modified by the user by using "customize" in configuration.yaml
b) Just because a thermostat supports a heat range of 44-99 doesn't mean I as a user of the thermostat want to allow that range. Most thermostats allow the limits to be customized by the owner.  I'd propose the same for HA.  Allow the user to set range limits.  For example, for my home thermostats I'd set heat limits to 55-71, for the garage 40-45 and I'd want the UI and the validation code to use there limits rather than the range the thermostat supports.

**Reply by kurdybanek** [reply]
refferring to point A), can you guide me how to change the UI limit?
I have one thermostat which has the limit of 50 degrees which I am using with the boiler. 
There is a workaround to use with automations by setting the temp via "set value of a Z-wave value" option, then defining proper parameters, but I can't manage it via UI or via regular climate action in automation

**Comment by PeteRager** [comment]
Branch that prototypes the changes for the base climate entity temperature that are being recommended. Note:  The zwave_js climate.py also need to be updated to return None instead of DEFAULT_MIN_TEMP and DEFAULT_MAX_TEMP ..

https://github.com/home-assistant/core/compare/dev...PeteRager:core:climate-range

**Comment by gjohansson-ST** [comment]
With this we seem to cure a symptom by making these optional for the validation.
As noted in the initial background it should be possible by the user to define the range but that's not included in the proposal, so the statement that this invalidates a cert requirement does still mean after this modification would be implemented, that the cert requirement is still not valid as the user can still not set the range.

Perhaps it's not a bad suggestion to make the validation optional (especially for generic integrations such as zwave) but the background for the issue seems incorrect.

**Comment by AlCalzone** [comment]
Just to add a new data point: https://github.com/zwave-js/node-zwave-js/issues/7472 reports a case where the thermostat is used to control the hot water temperature and can go up to 80 °C

**Reply by abmantis** [reply]
Is there no way for zwave-js to report the actual min/max for a device?

**Reply by alex3305** [reply]
@abmantis But what would be the _actual_ bounds?

**Reply by Nick-Sills** [reply]
> Is there no way for zwave-js to report the actual min/max for a device?

No, that's the problem here. Thermostats with a Setpoint Control Class of less than 3 don't report their Min/Max value. In my case, the Qubino Flush On/Off Thermostat accepts a setpoint in the range of -25 to +120 Degrees C, but the defaults in HA limit it to 0 to 50.

**Reply by abmantis** [reply]
I am not too familiar with zwave, but I recall it had a device database of some sort. Couldn't the min/max values for devices be defined there, just like Quirks for ZHA?
Even if we go ahead with this proposal (and I am not saying we should not), I feel like the right approach would be to actually have the proper values for devices so the users do not have to mess around and can just use the UI.

**Reply by Nick-Sills** [reply]
@abmantis I also thought this was a Z-Wave JS issue, but it seems that both Z-Wave JS and Zigbee2MQTT are meant to relay device data to consumers, in this case, Home Assistant, which then decides how to use it. I don't think adding constraints or extra parameters is really their role, though I would like to be wrong.

**Comment by kurdybanek** [comment]
I also have the same case - I use few qubino thermostats for both controlling radiators (here 50 C is sufficient) but also for controlling a water boiler. Which is doable via automation by using the "set value of a Z-Wave value" option, but not from UI.
Also using the action - climate:set temperature target doesn't work if the temperature is out of range.

**Comment by Nick-Sills** [comment]
I've added an HA issue and PR to update the default Max temp to 80 degrees. 

I agree with @AlCalzone on this situation, but right ow my Qubino ZMNHID Domestic Hot Water thermostats are  useless without hacking the source, so I've raised a PR and Issue:

https://github.com/home-assistant/core/issues/135439
https://github.com/home-assistant/core/pull/135442

Thanks!

**Reply by AJediIAm** [reply]
With the risk of giving a useless suggestion: a template climate entity might allow you to hack it in a more user friendly way https://github.com/jcwillox/hass-template-climate
I haven't gotten around to using the template climate myself, so apologies if it completely misses the point.

I general, I think a template climate entity is a good way to add functionally to stock standard stuff. Maybe a template is an alternative solution to the original problem.

**Reply by alex3305** [reply]
@AJediIAm No need for a custom component. This could also be done with a [Generic Thermostat](https://www.home-assistant.io/integrations/generic_thermostat/) if the controlled entity has a switch. Otherwise it should be pretty trivial to implement a [Template Switch](https://www.home-assistant.io/integrations/switch.template/) based on the current temperature and maybe some heuristics.

**Reply by AJediIAm** [reply]
In my case, there is no switch involved. The temperature is send directly to the heatpump. I wouldn't know how to use the generic thermostat here (which might be due to my lack of HA knowledge)

I have an automation which overrides the set temperature if it exceeds the min or max value, but not after generating a bunch of errors. It's workable, but I would rather prevent the wrong values being send in the first place.

**Reply by Nick-Sills** [reply]
> @AJediIAm No need for a custom component. This could also be done with a [Generic Thermostat](https://www.home-assistant.io/integrations/generic_thermostat/) if the controlled entity has a switch. Otherwise it should be pretty trivial to implement a [Template Switch](https://www.home-assistant.io/integrations/switch.template/) based on the current temperature and maybe some heuristics.

@alex3305 A Generic Thermostat requires a switch and there's no switch in a Climate entity. Besides, you can't link a Generic stat, or anything else, to update the thermostat set temp to above 50 degrees. The operational parameters of my Qubino stat for the set temp are actually -25 to +125 degrees C.  The only way to set a temp above 50 is to directly use Z-Wave JS.  

It doesn't matter how you try and implement it, the thermostat won't update the set temp, so it's useless for Hot Water Heating > 50 degrees with the current defaults without hacking `climate.py`.
<img width="500" alt="image" src="https://github.com/user-attachments/assets/5347b11e-10b9-46cc-87e9-4e7bdc1456e0" />

I think that updating the defaults to a sensible range for older thermostats that use Thermostat Setpoint Control Class less than 3 is absolutely the sensible thing to do.

**Reply by alex3305** [reply]
> Besides, you can't link a Generic [thermo]stat, or anything else, to update the thermostat set temp to above 50 degrees.

@Nick-Sills Yes you can. I use it with temperatures with my own set bounds.

![image](https://github.com/user-attachments/assets/f9d3f60a-5c72-4c19-86de-a06d18e7ab65)

```yaml
---
climate:
  - platform: generic_thermostat
    unique_id: climate_water_heater
    name: Water Heater
    heater: switch.temperature_water_heater
    target_sensor: sensor.temperature_water_heater
    min_temp: 25
    max_temp: 75
```

You could also template the heater to turn or off, even with a dynamic temperature. Something along the likes of this:

```yaml
switch:
  - platform: template
    switches:
      water_heater:
        value_template: "{{ is_state('climate.water_heater', 'heat') }}"
        turn_on:
          - action: climate.set_hvac_mode
            target:
              entity_id: climate.water_heater
            data:
              hvac_mode: "heat"
          # For my TRV I had to wait here
          - alias: "Wait until HVAC mode heat is activated..."
            wait_template: "{{ is_state('climate.water_heater', 'heat') }}"
            timeout:
              seconds: 5
          - action: zwave_js.set_value
            target:
              entity_id: climate.water_heater
            data:
              command_class: "67"
              property: setpoint-1
              value: >-
                {{ states('input_number.water_heater_temperature')
                      | float(60)
                      | round(1, 'half') }}
        turn_off:
          action: climate.set_hvac_mode
          target:
            entity_id: climate.water_heater
          data:
            hvac_mode: "off"
```

The `zwave_js.set_value` action doesn't use the climate input validation. Because it sets the setpoint in Z-Wave JS directly. I've used this back in October and November to update my thermostats.

**Reply by Nick-Sills** [reply]
@alex3305 Interesting, and thanks for sharing. 

I don't have a switch on my thermostat, **so not sure how 'Heat' and 'Off' would work. Besides, it's an abstraction hack that I **really** don't want to use and shouldn't be necessary. 

** As you say, I could make a template switch of course. :-)

**Reply by Nick-Sills** [reply]
@alex3305 I really appreciate your interest and help, but what exactly is your objection to raising the default max temp to 100 degrees? Thanks

**Reply by alex3305** [reply]
> I don't have a switch on my thermostat, so not sure how 'Heat' and 'Off' would work. 

That isn't a switch, but heating (or hvac) modes. Which should be supported by your ZMNHID if I'm reading the 
[manual](https://qubino.com/wp-content/uploads/2019/03/Qubino_Flush-On-Off-Thermostat-PLUS-extended-manual_eng_0.2.pdf) correctly. At least it should be Heat/Cool instead of Heat only. However you could also do it without heating modes, assuming the device only heats:

```yaml
switch:
  - platform: template
    switches:
      water_heater:
        turn_on:
          action: zwave_js.set_value
          target:
            entity_id: climate.water_heater
          data:
            command_class: "67"
            property: setpoint-1
            value: >-
              {{ states('input_number.water_heater_temperature')
                    | float(60)
                    | round(1, 'half') }}
        turn_off:
          action: zwave_js.set_value
          target:
            entity_id: climate.water_heater
          data:
            command_class: "67"
            property: setpoint-1
            value: 4   # or some other low value that turns the thermostat off
```

Heating and cooling could also be done through a switch, but that would be a bit more involved. But it can be done with tolerances within the generic thermostat component.

> Besides, it's an abstraction hack that I really don't want to use and shouldn't be necessary.

Sure I get that. I don't think it's a hack though. I think it's just a clever workaround for the moment. And unlike your statement earlier, it can be done 😉 .
