### DISCUSSION TITLE
Change the `variables` script action to update already defined variables in outer scopes

### DISCUSSION THREAD

**Discussion by emontnemery** [home-assistant/architecture#1208] [General] [answered]
## Summary of the proposal

Change the `variables` script action such that it updates variables which are already defined in outer scopes instead of defining local variables which shadows the variable from the outer scope.

This change is not backwards compatible and risks breaking existing scripts and automations and needs to be very prominently featured in release notes, if accepted

Core PR: https://github.com/home-assistant/core/pull/141114

### Example of the new behavior

```yaml
actions:
  - variables:
      x: 1
      y: 1
  - sequence:
    - variables:
        y: 2  # Updates y which exists in the outer scope
        z: 2  # Since z is not defined yet, it is assigned in the top-level scope
  - action: persistent_notification.create
    data:
      message: "{{ x }}, {{ y }}, {{ z }}" # x=1, y=2, z=2
      # Note; behaviour without this proposal is x=1, y=1, z undefined
```

## Motivation

* The current behavior is unintuitive and restrictive
  * It's very uncommon for an imperative programming language to not allow updating a variable defined in an outer scope
  * It's impossible to update variables in nested actions without resorting to helpers

* The current behavior is a bug
  * The `variables` script action was introduced by core PR [#39915](https://github.com/home-assistant/core/pull/39915). The PR  didn't test the behavior when assigning existing variables from an inner scope. @thomasloven confirms the implemented behavior was not intentional.

## Alternative solutions
1. Change the behavior of `variables` when setting variables
  a. Make a breaking change to `variables`; `variables` will update existing in-scope variables, and create variables which don't exist in the local scope
  b. Make a breaking change to `variables`; `variables` defaults to updating existing in-scope variables but add a flag to instead define local variables shadowing existing in-scope `variables`
  c.  Make a non-breaking change to `variables`; `variables` defaults to defining local variables shadowing existing in-scope `variables`
but add a flag to update existing in-scope variables
  d. Make a breaking change to `variables`; `variables` will update existing in-scope variables, and create a variables which don't exist in the outermost scope (which means there is essentially only one script global scope, except for the special `loop` and `wait` variables) (this proposal) 

2. Change the behavior of `variables` when defining variables
  a. Make a non-breaking change to `variables`; add a flag to to declare variables which may be updated from inner scopes

3. Add a new action, `assign_variables`, `assign_var`, `vars` or similar, which updates existing in-scope variables
   a. Keep the `variables` action as is
   b. Deprecate `variables` and add a second new action `set_local_variables` or similar which only sets local variables
   c. Deprecate `variables` and make the new action take a flag `local`  to only set local variables

#### 1b `variables` defaults to updating existing in-scope variables
```yaml
actions:
  - variables:
      x: 1
      y: 1
  - sequence:
    - variables:
        x: 2
        w: 2
      local: True
    - variables:
        y: 2
        z: 2
  - action: persistent_notification.create
    data:
      message: "{{ x }}, {{ y }}, {{ z }}" # x=1, y=2, z=2, w is undefined
```

#### 1c `variables` defaults to defining local variables
```yaml
actions:
  - variables:
      x: 1
      y: 1
  - sequence:
    - variables:
        x: 2
        w: 2
    - variables:
        y: 2
        z: 2
      local: False
  - action: persistent_notification.create
    data:
      message: "{{ x }}, {{ y }}, {{ z }}" # x=1, y=2, z=2, w is undefined
```

#### 1d `variables` will update existing in-scope variables, and create a variables which don't exist in the outermost scope
```yaml
actions:
  - variables:
      x: 1
      y: 1
  - sequence:
    - variables:
        y: 2  # Updates y which exists in the outer scope
        z: 2  # Since z is not defined yet, it is assigned in the top-level scope
  - action: persistent_notification.create
    data:
      message: "{{ x }}, {{ y }}, {{ z }}" # x=1, y=2, z=2; behaviour without this proposal is x=1, y=1, z undefined
```

#### 2a  add a flag to to declare variables which may be updated from inner scopes
```yaml
actions:
  - variables:
      x: 1
  - variables:
      y: 1
    global: True
  - sequence:
    - variables:
        x: 2  # Creates a local variable x because the variable x is not marked as global
        y: 2  # Updates y because it is marked as global
        z: 2  # Creates a local variable z
  - action: persistent_notification.create
    data:
      message: "{{ x }}, {{ y }}, {{ z }}" # x=1, y=2, z is undefined
```

#### 3a Add a new action, `set_variables`
```yaml
actions:
  - variables:
      x: 1
      y: 1
  - sequence:
    - variables:
        x: 2
        w: 2
    - set_variables:  # New actions which updates variables in outer scope
        y: 2
        z: 2
  - action: persistent_notification.create
    data:
      message: "{{ x }}, {{ y }}, {{ z }}" # x=1, y=2, z=2, w is undefined
```

#### 3b Add new actions, `set_variables` and `set_local_variables`
```yaml
actions:
  - variables:
      x: 1
      y: 1
  - sequence:
    - set_local_variables:  # New action with same behavior as `variables`
        x: 2
        w: 2
    - set_variables:  # New actions which updates variables in outer scope
        y: 2
        z: 2
  - action: persistent_notification.create
    data:
      message: "{{ x }}, {{ y }}, {{ z }}" # x=1, y=2, z=2, w is undefined
```

#### 3c Add new actions, `set_variables` with a flag
```yaml
actions:
  - variables:
      x: 1
      y: 1
  - sequence:
    - set_variables:
        x: 2
        w: 2
      local: True
    - set_variables:
        y: 2
        z: 2
  - action: persistent_notification.create
    data:
      message: "{{ x }}, {{ y }}, {{ z }}" # x=1, y=2, z=2, w is undefined
```

**Comment by arturpragacz** [comment]
The main proposal (1a) does not have consistent semantics. It should rather be:
```yaml
actions:
  - variables:
      x: 1
      y: 1
  - sequence:
    - variables:
        y: 2  # Updates y which exists in the outer scope
        z: 2  # Since z is not defined yet, it is assigned in the top-level scope
  - action: persistent_notification.create
    data:
      message: "{{ x }}, {{ y }}, {{ z }}" # x=1, y=2, z=2; behaviour without this proposal is x=1, y=1, z undefined
```

**Reply by tetele** [reply]
So basically all variables should become top-level?

**Reply by arturpragacz** [reply]
Yes, almost. There would still be some special variables like `repeat` which are not.

**Reply by tetele** [reply]
Personally, I don't see any inconsistency. I have no strong preference regarding whether smaller scoped variables should be allowed at all (i have never been in the position where i should use such variables), but I don't see what you regard as inconsistent.

**Reply by arturpragacz** [reply]
I think you are misunderstanding, I am not opposed to scoped variables. I just pointed out that the proposal 1a has flawed semantics.
The same action should not at the same time assign some variables, and locally define others, depending on the runtime behaviour.

**Reply by tetele** [reply]
OK, now I understand what you meant. Thanks for clearing that up!

**Reply by thomasloven** [reply]
I think it makes most sense to scope the variable on the entire script.
That's how e.g. python works:

```python
>>> def fn():
...   a = 1
...   if True:
...     a = 2
...     b = 3
...     print((a,b))
...   print((a,b))
... 
>>> fn()
(2, 3)
(2, 3)
>>> 
```

**Reply by emontnemery** [reply]
I've added this as an option 1d above.

**Reply by emontnemery** [reply]
By the way, doesn't option 2a also have the same issue with semantics as option 1a in the sense that a single `variables` action at the same time assigns some variables, and locally defines others?

**Reply by arturpragacz** [reply]
Yes, it does. Although they also differ in some important ways, proposal 1a seems to be significantly worse of the two, but given that 2a is under-specified, it is not 100% clear.

I think it would be wise not to waste our mental energy on those two, declare them as rejected, and focus on the remaining 6, that don't have those flaws, as that is still plenty options to decide.

I wrote below some advantages and disadvantages that I could think of. It would be interesting to hear an opposing perspective. Given that proposals 1b and 1d come with a downside of being a breaking change, they ought to have some important advantages that outweigh that drawback, that other proposals lack. Those should be listed and carefully evaluated.

**Comment by arturpragacz** [comment]
Given the fact that the local behaviour of `variables` action was there since the beginning and it was also explicitly documented in our official docs for years, I believe we should avoid a breaking change here, if we can. And we in fact can.

So my preference would be:
3b = 3c > 3a > 1c >>>> 1b > 1d

To expand on why:

Proposals 3b and 3c are very similar. The only difference is that one uses a local flag and the other separate action keywords. They both nicely distinguish between the two separate actions and are easy to type and immediately understand. They also both fully preserve backwards compatibility.

Proposal 3a is slightly worse, as from the old keyword `variables` it is not immediately obvious that it is local variables. Other than that it has the same advantages as 3b and 3c.

Proposal 1c is similar, but worse than 3c, because the more common action of assigning a variable requires more typing than defining a local variable. It should be the opposite. Other than that it is OK.

Proposals 1d and 1b are breaking changes and that's why I put them at the bottom. 1b is slightly better though, as it at least doesn't take away functionality and therefore makes it easier to quickly fix broken scripts. The preserved functionality can also be useful in some circumstances by itself.

Proposal 2a is quite weird and confusing, probably even broken when it comes to the edge cases, I'm also not aware of that kind of semantics being present anywhere else. I would not even consider it because of that.

Proposal 1a is fundamentally flawed as described in my comment above.

**Comment by thomasloven** [comment]
Since we discussed this a few weeks ago I've been thinking of the implications on introducing this as a breaking change.

I haven't looked into blueprints or automations or anything using `variables:`, but I would guess it is actually *very* uncommon. And that is probably because of this bug to be honest.
I would guess it's even mor uncommon to reuse variable names inside different scope.

It is documented, yes (unfortunately - likely another mistake by me), but I still think it's a bug that should be fixed.
And the documentation can have bugs too 🙄.

A second point: I don't think we should worry about scoping. This is not a programming language, and having all variables global makes things easier for the user.
Undefined variables can be handled with the `default` filter.

**Reply by arturpragacz** [reply]
Well, a documented bug becomes a feature.

We do need to solve it off course, the question is how exactly we do it. If there is a way to do it in a backwards compatible manner, I think that should be preferred.

>A second point: I don't think we should worry about scoping. This is not a programming language, and having all variables global makes things easier for the user.

On the one hand I agree, but on the other there are some special variables which do not have a global scope. So having some way to also define local variables explicitly would probably not be bad. Especially so when that would allow us to keep backwards compatibility.

**Reply by thomasloven** [reply]
You're right... I didn't think of variables like `wait` and `repeat`... maybe that's why I did it this way in the first place 🤔

**Reply by thomasloven** [reply]
That speaks strongly for solution 2a

**Reply by arturpragacz** [reply]
I would say it speaks for solution 3b or 3c, but maybe I'm not following what you mean.

**Reply by thomasloven** [reply]
As I see it 2a makes a change such that `variables` works as before *except* for variables which have been explicitly declared to be global.
That means it's not a breaking change, but an added feature. And its also the most minimal change which achieves this.

**Reply by arturpragacz** [reply]
All the proposals 1c, 3a, 3b, 3c are non-breaking and are basically an added feature. Only proposals 1a and 1b are breaking.

**Comment by thomasloven** [comment]
What would happen if

**2a add a flag to to declare variables which may be updated from inner scopes**
```yaml
actions:
  - variables:
      x: 1
  - variables:
      y: 1
    global: True
  - sequence:
    - variables:
        z: 2
        global: True
```
?
