### DISCUSSION TITLE
Add sliding door device type to binary sensor

### DISCUSSION THREAD

**Discussion by ebw44** [home-assistant/architecture#1210] [Entity Models] [answered]
The proposition is to add a 'sliding door' device type to the binary sensor to allow sliding doors icons similar to existing 'garage door' or 'window' device type.
A PR has already been proposed but has it changes the entity model it requires approval here.

For reference here are similar discussions:
https://github.com/home-assistant/architecture/discussions/645
https://github.com/home-assistant/architecture/discussions/690

**Comment by MartinHjelmare** [comment]
What integrations can leverage this device class? Please list the ones you find. Normally at least a handful of integrations are required to add a new device class, not counting custom integrations or MQTT, esphome, template etc. that can integrate anything.

**Comment by ebw44** [comment]
This device class can be used by any integration that integrates door sensors, a few examples are xiaomi, shelly, tuya (local and cloud), zigbee, aqara, sonoff, aeotec, fibaro...

**Reply by MartinHjelmare** [reply]
What code examples of sliding doors have you found? We need integrations that would use this in their code today if it was available. I don't know anything in the Z-Wave specification that talks about sliding doors, but I may have missed it.

**Reply by ebw44** [reply]
Most of the door sensors that use a reed switch can be used for sliding door as they are used for hinged door or windows.
My used case is only to have the dynamic sliding door icons in my dashboards without relying on custom card like below. Seeing most the device classes (garage door, window, door...) in binary sensor had this feature I thought it was one of the use case but may be I misunderstood the purpose of device class.
```
type: custom:config-template-card
variables:
  door_state: states['binary_sensor.living_room_door_opening'].state
entities:
  - binary_sensor.living_room_door_opening
card:
  type: entities
  entities:
    - entity: binary_sensor.living_room_door_opening
      name: Living room door
      icon: "${door_state === 'on' ? 'mdi:door-sliding-open' : 'mdi:door-sliding' }"
```
