### DISCUSSION TITLE
Support localizable blueprints

### DISCUSSION THREAD

**Discussion by karwosts** [home-assistant/architecture#1212] [General]
In blueprints, for the name and description of the blueprint, and for the name and description of input fields, can we support localization for these fields? Blueprint authors sometimes request a way to better support users who don't use HA in english language. 

I'm thinking that since those fields currently accept a string, we can optionally also support a dictionary, with keys as language codes, and values as the translated string in that language. E.g.:

```yaml
blueprint:
  name:
    en: Zone Notification
    de: Zonenbenachrichtigung
    es: Notificación de zona
  description:
    en: Send a notification to a device when a person leaves a specific zone.
    de: Senden Sie eine Benachrichtigung an ein Gerät, wenn eine Person eine bestimmte Zone verlässt.
    es: Envía una notificación a un dispositivo cuando una persona abandona una zona específica.
 ```
 
We would then use the user profile language in the frontend to select which string to display, falling back to English if no matching language exists (would make `en` key required as the fallback).
