### DISCUSSION TITLE
Update Media Selector to allow selecting media without an entity ID

### DISCUSSION THREAD

**Discussion by balloob** [home-assistant/architecture#1217] [General] [answered]
# Context

The [Media Selector](https://www.home-assistant.io/docs/blueprint/selectors/#media-selector) was created to allow the user to pick media to play on a media player.

It requires the user to select a media player, and then the frontend will query the `MediaPlayer.async_browse_media` entity method to show available media to pick. Internally, the media player will call the media source API and optionally combine it with their own sources.

Two recent use cases have come up where we want the user to pass media, without requiring it first to pick a media player:

* As per https://github.com/home-assistant/architecture/discussions/1213, a user can set the pre-announcement media for `assist_satellite.start_conversation` and `assist_satellite.announce`. These actions currently use a text selector because there is no attached media player.
* Proposal https://github.com/home-assistant/architecture/discussions/1201 looks into expanding the media source integration to send media to LLMs. The `conversation.process` action will need to be expanded with an option to allow the user to pick the media to attach to a conversation. The media selector is the best fit for this.

# Proposal

_PR implementing this proposal: https://github.com/home-assistant/core/pull/145527_

We update the Media selector to allow specifying file filters. When a file filter is specified, it will not allow the user to pick an entity and the `entity_id` field in the response is omitted. File filters are specified by via the new `accept` option to specify the types of data that it can accept.  

```yaml
media:
  accept:
    - "image/jpeg"
    - "image/png"
``` 

This proposal is backwards compatible because it requires a new selector option to be set.

## Current media selector

```yaml
media:
```

and response

```yaml
entity_id: media_player.living_room
media_content_id: media-source://tts/cloud?message=TTS+Message&language=en-US&gender=female
media_content_type: audio/mp3
metadata:
  title: TTS Message
  thumbnail: https://brands.home-assistant.io/_/cloud/logo.png
  media_class: app
  children_media_class: null
  navigateIds:
    - {}
    - media_content_type: app
      media_content_id: media-source://tts
    - media_content_type: audio/mp3
      media_content_id: >-
        media-source://tts/cloud?message=TTS+Message&language=en-US&gender=female
```

## Media selector with accept specified

```yaml
media:
  accept:
    - audio/*
```

and response

```yaml
media_content_id: media-source://tts/cloud?message=TTS+Message&language=en-US&gender=female
media_content_type: audio/mp3
metadata:
  title: TTS Message
  thumbnail: https://brands.home-assistant.io/_/cloud/logo.png
  media_class: app
  children_media_class: null
  navigateIds:
    - {}
    - media_content_type: app
      media_content_id: media-source://tts
    - media_content_type: audio/mp3
      media_content_id: >-
        media-source://tts/cloud?message=TTS+Message&language=en-US&gender=female
```

# Consequences

Easier for users to select alternative audio for announcements.

# Alternatives

We create a new media source selector. It would be an exact copy of the media selector except for the `entity_id: null` in the response.

# Updates

- April 1, 2025: Original proposal
- April 22, 2025: Updated to make it a new selector meant for just media sources.
- May 15, 2025: Merge logic into the media selector
