### DISCUSSION TITLE
Proper release notes for updates

### DISCUSSION THREAD

**Discussion by zweckj** [home-assistant/architecture#1245] [General]
This is building on a proposal from 6 years ago, that was never answered nor implemented <https://github.com/home-assistant/architecture/discussions/897>

## Summary

With Home Assistant targeting a broader, less tech savvy user base, we should make it easier in the update process to make it clear to users what is included in the update they are about to install.
This especially means:

* clearly marking breaking changes for integrations that the user actually uses, without requiring the users to go the blog and scan through it
* making minor changes & improvements transparent to the users in language they can understand (also without going through the blog, or even worse - scanning through PRs for changes that are not covered in the blog

## Proposal 
To enable this, we'd need to require contributions to existing integrations to properly fill out a change log in their PRs.

### Option 1
Keep the structure suggested by @balloob back in 2019 in the original architecture discussion

```yaml
domain: mqtt
changelog:
- release: 2025.7.0
  author: "@balloob"
  breaking_change: true
  change: >
    The internal MQTT broker has been moved out of the `mqtt` integration and is now part of a new `mqtt_broker` integration. To set it up, update your configuration as follows:

    ```yaml
    mqtt_broker:
      password: bla

    mqtt:
      host: localhost
      username: homeassistant
      password: bla
    ```
```

We'd adapt CI to fail unless those are filled out correctly. If we deem it to much of a burden for contributors we can also think about trying to auto-generate those through GitHub CoPilot if the file is not touch as part of the PR.

### Option 2
We could also add a separate `Release notes` section to the PR template to separate end user changes from technical PR description. We'd during release we'd then pull all those change into a single `release_notes.json` file for that specific release. We could then use github tags to exclude non-relevant changes (code quality).

## Open questions

* How would we attach those changelogs in the individual releases? 
    * Would we put them inside the artifact?
    * Render it to the release notes?
    * Query from GitHub directy -> this sounds like a bad idea?
* Instead of adding the release to the yaml, we could also add the PR number as an identifier, that way we would be able to clearly determine what is part of a release or not, by the commits included in the release. This would cover cases where PRs are removed from the release during cutting it because of merge conflicts (patch releases).
* Instead of using a yaml file we could also add a separate `Release notes` section to the PR template to separate end user changes from technical PR description. This would probably mean we'd need to parse them before the release and put it somewhere for consumption.
* How would we handle localization? Not localize at all, or use (and prominently announce that) LLM base automated translations.
