### DISCUSSION TITLE
YAML documentation formatting and standards

### DISCUSSION THREAD

**Discussion by frenck** [home-assistant/architecture#495] [Documentation] [answered]
## Context

Across the documentation, there is a wild different use of standards when writing YAML. Especially newer users might get confused by "older" methods (e.g., things we needed templates for back in the day). But also different ways to write YAML in the same way.

## Proposal

I want to make an effort into making it look consistent and "best" practice for the end-users.

Some goals:

- Have a consistent style.
- Avoid confusion between different YAML scalar types.
- Show best practices for both YAML & Home Assistant usage.
- Some things in Home Assistant can be done in more ways, pick the best one.

### YAML

Basic YAML usage; no specific rules for our features. This is fully compatible with the styling Prettier applies.

- Indentation of 2 spaces.

  ```yaml
  # Good
  example:
    one: 1

  # Bad
  example:
      bad: 2
  ```

- Only allow for `true` and `false` (lower case) for YAML booleans, no truthy values.
   This keeps it compatible with YAML 1.2 (that dropped support for several unquoted; `y`/`n`/`yes`/`no`/`on` and similar). Additionally, it helps to avoid confusion with `on`, or `no` for people from Norway.

   ```yaml
  # Good
  one: true
  two: false
  
  # Bad
  one: True
  two: on
  three: yes
  ```
  
- Comments must match the current indentation level.

  ```yaml
  # Good
  example:
    # Comment
    one: true
  
  # Bad
  example:
  # Comment
    one: false
  ```

- Block style sequences, must be indented under the key.

  ```yaml
  # Good
  example:
    - 1
    - 2
    - 3
  
  # Bad
  example:
  - 1
  - 2
  - 3
  ```

- Flow style sequences have space after each comma `,` and no white space before opening and closing:
  
  ```yaml
  # Good
  example: [1, 2, 3]

  # Bad
  example: [ 1,2,3 ]
  example: [ 1, 2, 3 ]
  example: [1,2,3]
  ```

  The use of flow style should be avoided, while the above example is simple, short and clean. With longer data in it, it becomes long and harder to read quickly.

- Mappings must be block style, flow style mappings should not be used,

  ```yaml
  # Good
  example:
    one: 1
    two: 2

  # Bad
  example: { one: 1, two: 2 }
  ```

- Null values should be implicitly marked.

  ```yaml
  # Good
  example:

  # Bad
  example: ~
  example: null
  ```

- Strings are preferably quoted with double quotes (`"`)
  
  ```yaml
  # Good
  example: "Hi there!"

  # Meh...
  example: Hi there!

  # Bad
  example: 'Hi there!'
  ```

### Home Assistant specific YAML

Within Home Assistant, we also have some things that can be done in different ways, while still adhering to the above set styling. This part is here to take care of that.

### Basics

- String are double quoted. Exempted from this rule are:
  - Entity IDs
  - Entity attributes
  - Device IDs
  - Area IDs
  - Condition types (e.g., `numeric_state`, `state`)
  - Trigger platforms (e.g., `state`, `time`)
  - Service names (e.g., `light.turn_on`)
  - Event names
  - Values that accept a limited set of possible, hardcoded values.
    For example, `mode` in automations.

  ```yaml
  # Good
  action:
    - service: notify.frenck
      data:
        message: "Hi there!"
    - service: light.turn_on
      target:
        entity_id: light.office_desk
        area_id: living_room
      data:
        transition: 10

  # Bad
  action:
    - service: "notify.frenck"
      data:
        message: Hi there!
  ```

- Default values should not be part of the YAML.

  ```yaml
  # Good
  - alias: "Test"
     trigger:
       -  platform: state
           entity_id: binary_sensor.motion

  # Bad
  - alias: "Test"
     trigger:
       -  platform: state
           entity_id: binary_sensor.motion
     condition: []
  ```

### Service targets

If you want to fire a service call towards an entity ID (for example, to turn on a light), you can do so in three different ways.

The entity ID can be specified as a property of the service level, part of the data that is sent towards service call or as an entity in a service target.

This is confusing for some and had lead to different topics on the forum, issues, and completely different usages across the documentation.

Service targets have been introduced recently, as part of Blueprints and allow one to target a service call towards an entity, device or area. And is, therefore, the most flexible of the options available.

The suggestion is to adjust all documentation to use this consistently.

```yaml
# Good
action:
  - service: light.turn_on
    target:
      entity_id: light.living_room
  - service: light.turn_on
    target:
      area_id: light.living_room
  - service: light.turn_on
    target:
      area_id: living_room
      entity_id: light.office_desk
      device_id: 21349287492398472398

# Bad
action:
  - service: light.turn_on
    entity_id: light.living_room
  - service: light.turn_on
     data:
       entity_id: light.living_room
```

### Properties that accept a scalar or a list of scalars

We have a lot of places that access both a scalar value or a list of scalar values, additionally, sometimes, we even accept a comma-separated string value as a list.

- Putting multiple values in a single scalar value (comma separated string) must not be used.
- The use of a single scalar value is allowed.
- A list with a single scalar value should not be used.
- If a list is used, it must be block style.

```yaml
# Good
entity_id: light.living_room
entity_id:
  - light.living_room
  - light.office

# Bad
entity_id: light.living_room, light.office
entity_id: [light.living_room, light.office]
entity_id:
  - light.living_room
```

### Properties that accept a mapping or a list of mappings

Additional to the lists above, we also have properties that accept both a mapping or a list of mappings. Well known examples are: `condition`, `action`, `sequence`.

In case a property accepts a single mapping or a list of mappings, a list of mapping must be used. Even when a single mapping is passed in.

This makes it easier to understand one can add more items to it and easier to copy and paste a single item into your own code.

```yaml
# Good
action:
  - service: light.turn_on
    target:
      entity_id: light.living_room

# Bad
action:
  service: light.turn_on
  target:
    entity_id: light.living_room
```

### Templates

The use of templates should be avoided. If there is a pure YAML version available, this should be used. It is easier to follow for the less technical user.

It also removes the need for escaping it from the liquid template engine our website uses.

```yaml
# Good
condition:
  - condition: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: 4

# Bad
condition:
  - condition: template
    value_template: "{{ state_attr('sun.sun', 'elevation') < 4 }}"
```

Additionally, long lines in templates should be avoided and split across multiple lines to make more clear what happens.

```yaml
# Good
value_template: >-
  {{
    is_state('sensor.bedroom_co_status', 'Ok')
    and is_state('sensor.kitchen_co_status', 'Ok')
    and is_state('sensor.wardrobe_co_status', 'Ok')
  }}

# Bad
value_template: "{{ is_state('sensor.bedroom_co_status', 'Ok') and is_state('sensor.kitchen_co_status', 'Ok') and is_state('sensor.wardrobe_co_status', 'Ok') }}"
```

Finally, prefer shorthand style templates over-expressive format, as they
provide a cleaner syntax.

```yaml
# Good
condition:
  - "{{ some_value == some_other_value }}" 

# Bad
condition:
  - condition: template
    value_template: "{{ some_value == some_other_value }}"
```

We do not allow the use of the states object directly if a helper method is available. For example now allowing `states.sensor.temperature.state`, instead use `states('sensor.temperature')`.

This applies to  `states()`, `is_state()`, `state_attr()` and `is_state_attr()`, to avoid errors and error message when the entity isn’t ready yet (e.g., during Home Assistant startup).

Spacing around the filter pipe marker ` | ` is required. If this makes readability unclear, the use of additional parentheses is recommended.

```yaml
# Good
condition:
  - "{{ some_value | float }}" 
  - "{{ some_value == (some_other_value | some_filter) }}" 

# Bad
condition:
  - "{{ some_value == some_other_value|some_filter }}" 
```

Finally, templates are strings, and thus are double-quoted. As a result of that, single quotes should be used inside the template.

```yaml
# Good
condition:
  - "{{ 'some_value' == some_other_value }}" 

# Bad
condition:
  - '{{ "some_value" == some_other_value }}'
```

## Consequences

Tons of examples to adjust, but at least we have something to hold on to.
