### DISCUSSION TITLE
Proposal: blueprints selectors with multiple integration, domain and device_class filters

### DISCUSSION THREAD

**Discussion by EPMatt** [home-assistant/architecture#499] [Entity Models] [answered]
Hi there!

I'd like to propose an extension for the blueprint selectors which are currently available, specifically for `area`, `device`, `entity`, `target` selectors.

I think limiting the selection just to one `integration`, `domain`, `device_class`, `model`, `manufacturer` filters can be a problem with more "generic" blueprints.

For example, let's think about a blueprint which targets both ZHA and deCONZ devices. There's no way to specify a filter to allow an input for either one of these two integrations. Of course the filter could be relaxed, but this has the disadvantage of allowing users to put whatever input they want (potentially not supported or invalid for the current blueprint).  

## Proposal

The core idea is to allow multiple options for the filters specified above. For example the following entity selector:

```yaml
entity:
  integration:
  - zha
  - deconz
  domain: light
```
would allow to input all light and switch entities provided either by the ZHA or deCONZ integration. 

This should not be a Breaking Change though: users should still be able to specify a single option for those filters with the current syntax, that is:
```yaml
entity:
  integration: zha
  domain: light
```

**Comment by frenck** [comment, marked as answer]
Going through the architectural discussions and ran into this one. This has actually been "fixed", implemented and available in a recent version of Home Assistant.

These selects now accept a list of filters. You can pass multiple filters to selectors, the combination of them all is shown.

For example:

```yaml
entity:
  filter:
    - integration: zha
      domain: light
    - integration: deconz
      domain: light
```

../Frenck
