### DISCUSSION TITLE
Add `light.adjust` service call

### DISCUSSION THREAD

**Discussion by chishm** [home-assistant/architecture#537] [Entity Models]
I'd like to add a new service call to `LightEntity`s to change the state (brightness, color, effect, etc.) of lights that are already on, without turning on lights that are off. The default implementation in the `LightEntity` base class would be:
```py
async def async_adjust(self, **kwargs):
    if self.is_on:
        self.turn_on(**kwargs)
```

This is how scripts can implement such a feature at the moment, with something like:
```yaml
script:
 - condition: state
   entity_id: light.my_light
   state: 'on'
 - service: light.turn_on
   data:
     entity_id: light.my_light
     brightness_pct: 50
```

# Benefits over the above approach

## 1. Light groups can be adjusted without turning on all members

For example, I could have a light group containing all the lights in my house. At night I could change the color temperature to something warm, but only for the lights that are on.

Not all "light groups" expose their individual members (e.g. Zigbee groups), so it is currently impossible to adjust only the members that are currently on.

## 2. More efficient implementation for some integrations
Zigbee supports addressing an entire group with one adjust message. To replicate this currently requires a message to each on light individually.

## 3. Simpler scripts
The above script could be simplified to:
```yaml
script:
 - service: light.adjust
   data:
     entity_id: light.my_light
     brightness_pct: 50
```

For scripts controlling many lights, this removes the need for looping over them, as the list of lights could be supplied in the `entity_id` parameter.

# What I would do
1. Implement the base service in `LightEntity`.
2. Update documentation.
3. Implement a specialisation for the `deCONZ` integration.
4. Help anyone who wants to implement specialisations for other integrations.
