### DISCUSSION TITLE
Cover: when using position_template, allow value_template only for "opening" and "closing" states

### DISCUSSION THREAD

**Discussion by ruggi99** [home-assistant/architecture#582] [Entity Models] [answered]
I think it would be nice to add a new state to cover. We now have 4 states: open, closed, opening and closing.
I use a template cover because I'm using a device which is not suitable for covers and therefore I have no feedback.
I use a timer to know if the cover is fully closed or fully open (I know that's not the best thing to do).
We all know that we can't use both value_template and position_template in a template cover.
The problem I have is that I can't have a "middle" state where the cover is not fully open or fully closed.
So using a value_template I have to use open and closed state, which always disables the opening or closing direction.
And using position_template I could fix this but I'll lose the opening and closing states (needed for a better UI feedback).
So a "middle" state will be a solution IMHO.
EDIT: related home-assistant/frontend#9102

**Comment by thecode** [comment]
You can use `position_template`, set the `position_open` to 2, so you will have 3 positions:
0 = closed
1 = "middle"
2 = fully open
So that you don't loose the UI feedback.

Here you can find some examples:
https://www.home-assistant.io/integrations/cover.mqtt/#full-configuration-using-entity_id--variable-in-the-template

The position and and state templates can share the same topic or you can set the position from the state topic.
If you can post what payloads and topic you have to indicate the 3 states I can prepare an example configuration.

**Reply by ruggi99** [reply]
As said above I'm using a device that is not suited for covers.
It's a device that has two independent outputs (it's for lights).
All I have is a command topic and a state topic for the outputs.
Instead of using a MQTT cover (that is limited in my case) I prefer using a template cover and controlling it with Node-RED.
For the position_template I'm using a input_number as a helper

**Reply by thecode** [reply]
The fact that you use a device that is not suited for covers is ok, but even if the entity model will have a "middle" state you will have to somehow send an MQTT payload that will set the entity to `closed`, `opened` or `middle`. How do you plan to do it?

**Reply by ruggi99** [reply]
I don't get what you are talking about.
All I do is trying to maintain a sort of internal state, like home-assistant in optimistic mode, but better.
Currently I'm using an automation to trigger an event every time a direction is selected (there's also a a 2-way button near the cover).
That event is caught by node-red that starts a timer. Meanwhile the state must be opening or closing.
When the timer runs out, I know (not for sure obviously) that the cover is fully open or fully closed.
But here comes the problem. If I stop the cover before the timer runs out I would like to put the cover in the "middle" state.
Using only "open" and "close" state, frontend always disables a direction base on the state.
So I can move the cover up or down. As said the problem is solved by using position_template, but there I don't have opening or closing states.
Node-red then calls input_numer.set_value service for the helper I described above.
I don't send any payload and I don't understand why I would do that.
As a note: In the frontend code there's a function called `isFullyOpen` that checks, if the position is available, if the state is "open". But, in my opinion, for the backend "open" means not fully closed, so it's not the same thing. It lacks a third state, not fully open and not fully closed.

**Reply by emontnemery** [reply]
@thecode: @ruggi99 is not using mqtt cover, it's instead a template cover.

**Reply by thecode** [reply]
> @thecode: @ruggi99 is not using mqtt cover, it's instead a template cover.

I understood that later, but the same advice about using the position as 3 states will also work with a template cover:
0 = closed
1 = "middle"
2 = fully open

**Reply by emontnemery** [reply]
Yes, but in that case there's no direction feedback (opening / closing), I _think_ that's what @ruggi99 meant:
> using position_template I could fix this but I'll lose the opening and closing states (needed for a better UI feedback)

@ruggi99 can you confirm?

**Reply by ruggi99** [reply]
Yeah I confirm.

> 0 = closed
> 1 = "middle"
> 2 = fully open

How could this be reached in a template cover?

**Reply by emontnemery** [reply]
Restricting the range to 0..2 is a feature of MQTT cover, for template cover the range is not configurable but you can do something like:
0 = closed
50 = "middle"
100 = fully open

How could this be

**Reply by ruggi99** [reply]
Yeah that's what i'm making now.
But from the message from thecode I thought this was configurable

**Comment by emontnemery** [comment, marked as answer]
Let's not complicate the base component with additional when the problem is limitations in template cover.

Template cover could allow combining a value template with a position template, with the valid output from a value template restricted to "opening" and "closing".

**Comment by ruggi99** [comment]
@emontnemery Yeah, I understand what you mean. I think your idea is valid

> In the frontend code there's a function called isFullyOpen that checks, if the position is available, if the state is "open". But, in my opinion, for the backend "open" means not fully closed, so it's not the same thing. It lacks a third state, not fully open and not fully closed.

But this could be a general problem now or in the future. As said, home-assistant lacks a "middle" state (in value_template) where the cover is not fully open or fully closed and implementing this change is so small (from what I saw and I know) that it's worth it

**Reply by emontnemery** [reply]
That's pretty much the point of the `position` attribute:
100: fully open
99..1: not fully opened or fully closed (this is your "middle" state)
0: fully closed

**Reply by ruggi99** [reply]
Ok. So as you said, a combination of value and position attributes will "cover" all possible states?

**Reply by emontnemery** [reply]
Nice pun 👍

**Reply by ruggi99** [reply]
Thank you all

**Comment by thecode** [comment]
Here is the example I was trying to explain:
```yaml
input_number:
  garage_door_position:
    name: Garage Door Position
    initial: 0
    min: 0
    max: 100
    step: 50

cover:
  - platform: template
    covers:
      garage_door:
        device_class: garage
        friendly_name: "Garage Door"
        position_template: "{{ states('input_number.garage_door_position') }}"
        open_cover:
          - condition: numeric_state
            entity_id: input_number.garage_door_position
            below: 100
          - service: switch.turn_on
            target:
              entity_id: switch.garage_door
        close_cover:
          - condition: numeric_state
            entity_id: input_number.garage_door_position
            above: 0
          - service: switch.turn_off
            target:
              entity_id: switch.garage_door
        stop_cover:
          service: switch.turn_on
          target:
            entity_id: switch.garage_door
```

I use input number as something to store the current cover state:
close = 0
"middle" = 50
open = 100

There are other methods to store the state, I just choose something simple to explain.

Now if I set the `input_number.garage_door_position` to 0 the `close` button will be disabled, if I set it to 50 both `close` and `open` are enabled, if set to 100 `open` is disabled.

How do you combine it with node-red:
When you catch the event which is used to start the timer, node-red should call a service to set the `input_number.garage_door_position` to 50, this will show the cover in the "middle" state, when your timer ends and the cover is either fully open or fully close call the `input_number.garage_door_position` again with the correct state (0 for closed and 100 for opened)

Hope is is more clear now.
