### DISCUSSION TITLE
device_tracker: bring back firing an event when a new device is found

### DISCUSSION THREAD

**Discussion by mbo18** [home-assistant/architecture#586] [General]
Device_tracker integrations used to fire an event (device_tracker_new_device) when a new device were found: https://github.com/home-assistant/core/blob/dev/homeassistant/components/device_tracker/legacy.py#L121

With device tracker refactoring back in 2019 firing this event has been dropped. I'm using the nmap_tracker integration which has just been rewritten and I'm now unable to get a notification when a new device is connected to my network.

Is it possible to add this event back?

Related issue: https://github.com/home-assistant/core/issues/52362

**Comment by Mariusthvdb** [comment]
agreed, as a few other important aspects of those new devices are lost in the frontend: (Mac_address to name the most important one)

this was  pretty important:
```
      service: persistent_notification.create
      data:
        title: >
          Newly tracked: {{trigger.event.data.entity_id}}
        message: >
          New device tracked: ({{trigger.event.data.entity_id}})
          Host: {{trigger.event.data.host_name}}
          Mac-address: {{trigger.event.data.mac}}
```

**Comment by frenck** [comment]
So, how about a more generic solution.

We already have events for all kinds of things, as a new integration found.

<https://www.home-assistant.io/docs/configuration/events/>


Maybe we should add: New entity added?

**Reply by Mariusthvdb** [reply]
won't that fire 35 times when eg Buienradar is configured, or even more on a Synology Diskstation......and those entities (sensors in this case) are quite self-explanatory.

it's the domain `device_tracker` that require the special attention and details.

**Reply by frenck** [reply]
You are now thinking limited to your own situation. If you are interested in just device trackers, you can filter the events on that.

I might be interested in sensors 🤷 

Events have data :)

**Reply by Mariusthvdb** [reply]
yes, I guess thats fair. 
I don't object at all to adding a "new entity added" event of course! I can see the advantage in that, and have been wondering about the new _lights_ eg getting added without notification.
This new event could realize notifications I those cases too, which is great. Improvement overall.

I guess it all depends on the data object, and I sincerely hope the fields in that data object for an entity of the domain `device_tracker` will again contain `hostname` and `mac`.

**Reply by frenck** [reply]
I think adding the entity ID to the data should be sufficient. At that point, no matter the entity, the states can be fetched.

**Reply by Mariusthvdb** [reply]
Of course, I see that.

I was merely saying that, because I would hope the new devices will get those  properties/attributes soon. And,  with this new event, we could immediately see that not only the state `device_tracker.macbook_4` was added, as they are now called, but also push these attributes. (Instead  having to check the `core.entity_registry` for all other info , to be able to determine which is which ...)

**Reply by chemelli74** [reply]
> I guess it all depends on the data object, and I sincerely hope the fields in that data object for an entity of the domain `device_tracker` will again contain `hostname` and `mac`.

Those info are already there as attributes of the new `ScannerEntity`. Am I missing something ?

Simone

**Reply by Mariusthvdb** [reply]
Probably me missing it.. ,-) you're saying we can already alert on an event 'new entity'? And that that new entity event has attributes for the entity/domain etc etc ?

**Reply by chemelli74** [reply]
nope, just speaking about the attributes ;-)

Simone

**Reply by chemelli74** [reply]
I came up with this:

```yaml
- alias: New network device
  id: new_network_device
  trigger:
    - platform: event
      event_type: entity_registry_updated
  condition:
    - "{{ trigger.event.data.action == 'create'}}"
    - "{{ trigger.event.data.entity_id.startswith('device_tracker') }}"
  action:
    - service: system_log.write
      data:
        message: "New network device: {{ trigger.event.data.entity_id.replace('device_tracker.', '') }}"
        level: warning
        logger: homeassistant.components.device_tracker
    - service: notify.mobile_app_myphone
      data:
        message: "New network device: {{ trigger.event.data.entity_id.replace('device_tracker.', '') }}"
```

Sure something better can be done, but it's a start ;-)

Simone

**Reply by Mariusthvdb** [reply]
Hey Simone,

let me post what we did today on Discord:
```
  - alias: New device registered
    id: New device registered
    mode: queued
    trigger:
      platform: event
      event_type: entity_registry_updated
      event_data:
        action: create
    condition: >
      {{trigger.event.data.entity_id.startswith('device_tracker')}}
    action:
      - variables:
          entity: >
            {{trigger.event.data.entity_id}}
      - service: system_log.write
        data:
          message: >
            New device registrered: {{state_attr(entity,'friendly_name')}}
          level: warning
          logger: homeassistant.components.device_tracker
      - service: persistent_notification.create
        data:
          title: >
            New device registered: {{state_attr(entity,'friendly_name')}}
          message: >
            Entity: {{entity}}
            Host: {{state_attr(entity,'host_name')}}
            Ip: {{state_attr(entity,'ip')}}
            Mac-address: {{state_attr(entity,'mac')}}
            Id: {{device_id(entity)}}
```

maybe something could be done with the device_registry_updated, but I havent tested that yet. For now this brings back all functionality of the 'old' automation, and a bit more (ID) because of the new template option for device_id

**Reply by chemelli74** [reply]
@Mariusthvdb we should transform this in a blueprint and provide it with core.

**Reply by Mariusthvdb** [reply]
Never made a blueprint.... but this would be a great first ;-)

**Reply by chemelli74** [reply]
With the changes introduced by [Make device tracker entities work better](https://github.com/home-assistant/core/pull/63328) , this is no longer working.

Any idea for an alternative solution ?

Simone

**Comment by mbo18** [comment]
Having events for all newly added entities would really be a great feature 👍👍👍
We should be able to filter by integration and/or by device name. 
Should I rename this discussion title to a more generic one?

**Reply by thecode** [reply]
Yes

**Reply by Mariusthvdb** [reply]
tbh, I feel you shouldn't, because this will be seen by many people losing the ability to track their new devices.... it was specifically triggered by that, and having that in the title is valuable information

not withstanding Frenck making it into something even better

**Comment by Mariusthvdb** [comment]
not being a dev, I wouldn't dare to start picking up what Bdraco already had picked up in https://github.com/home-assistant/core/pull/52409 and was taken down.
Now the Nmap tracker will be in 2021.9 in the new style, would this be a fine moment to develop the new HA global new entity Event? Goes without saying Id be glad to assist in any way I can.

**Comment by Mariusthvdb** [comment]
Ever since the [new device_tracker behavior](https://github.com/home-assistant/core/pull/63328) has been merged, we can no longer use the event suggested above to create the 'New device tracked' automation, because the event.data are no longer populated for devices that dont have a config entry (and these device_trackers are not enabled upon discovery). Ive filed that in an issue at https://github.com/home-assistant/core/issues/65188 

this would seem collateral damage of the new behavior, and hoping this can be restored, so an automation with full data set can be used once again.

ill post that automation here, so nobody has to navigate away:
```
  - alias: New device registered
    id: New device registered
    mode: queued
    trigger:
      platform: event
      event_type: entity_registry_updated
      event_data:
        action: create
    condition: >
      {{trigger.event.data.entity_id.startswith('device_tracker')}}
    action:
      - variables:
          entity: >
            {{trigger.event.data.entity_id}}
      - service: system_log.write
        data:
          message: >
            New device registrered: {{state_attr(entity,'friendly_name')}}
          level: warning
          logger: homeassistant.components.device_tracker
      - service: persistent_notification.create
        data:
          title: >
            New device registered: {{state_attr(entity,'friendly_name')}}
          message: >
            Entity: {{entity}}
            Host: {{state_attr(entity,'host_name')}}
            Ip: {{state_attr(entity,'ip')}}
            Mac-address: {{state_attr(entity,'mac')}}
            Id: {{device_id(entity)}}
```

most fields are empty (None) except for the entity_id.
