### DISCUSSION TITLE
Sensor can only be of measurement type or increasing; they don't have to be

### DISCUSSION THREAD

**Discussion by jyavenard** [home-assistant/architecture#623] [Entity Models] [answered]
The problem with `last_reset` attribute being deprecated and the move in favour of using a state_class `STATE_CLASS_TOTAL_INCREASING` (see https://developers.home-assistant.io/blog/2021/08/16/state_class_total/) 

which indicates ```For sensors with state_class STATE_CLASS_TOTAL_INCREASING, a decreasing value is interpreted as the start of a new meter cycle or the replacement of the meter. It is important that the integration ensures that the value cannot erroneously decrease in the case of calculating a value from a sensor with measurement noise present. This state class is useful for gas meters, electricity meters, water meters etc.```

This leaves no room for sensors that always present a negative value and that will accumulate, or sensors whose sums only ever decrease.

A practical use is with energy sensors where the sign indicates which way the current is flowing.
A device like the iotawatt measures signed current and from the voltage determines the power (P=UI).

As such, an energy production system whose current flow upstream (like when exporting energy back to the grid) will be recorded as a negative sensor that keeps growing.

The `integration` integration is an example of sensor that can easily produce a monotonically decreasing value over time.

In addition to `STATE_CLASS_TOTAL_INCREASING` there should be a `STATE_CLASS_TOTAL_DECREASING` but as it's close to impossible to determine upfront which type of sensor we would have at the time it will be created, ideally we should have `STATE_CLASS_TOTAL_MONOTONIC`.
and the type should be `total_monotonic`

To determine rollover or sensor reset, one has to detect if the difference between the last recorded value and the next value has a different sign.

**Comment by emontnemery** [comment]
In general, this makes sense, but there are two edge cases which makes this tricky:
- How can we reliably detect if a monotonic value is increasing or decreasing
- There is currently a workaround in place which makes a `total_increasing` sensor not reset if the relative difference between two consecutive states is < 10%, documented here https://developers.home-assistant.io/docs/core/entity/sensor#state-class-total_increasing

Also, please note that Home Assistant's energy dashboard expects all energy sensors to have a positive value; both export and import sensors should have a positive value.

**Reply by jyavenard** [reply]
The sign of the series is determined as soon as you have two values.
```
bool is_increasing = state[1] > state[0] # stored forever
bool reset = (state[n] > state[n-1]) != is_increasing
if reset:
  ...
```
I'm not familiar in the context in which it will be used, and I don't see at a glance why ignoring small changes would make a difference here.

I'm aware of the energy dashboard requirement ; this can be worked around by using a template, which isn't particularly user friendly either. I had to do the following:
```
sensor:
  - platform: template
    sensors:
      energy_solar_abs:
        friendly_name: "Solar Energy Abs"
        value_template: "{{ states('sensor.total_solar_wh_accumulated')|float|abs}}"
        unit_of_measurement: Wh
        device_class: energy
        attribute_templates:
          state_class: "{{ state_attr('sensor.total_solar_wh_accumulated', 'state_class') }}"

      energy_export_abs:
        friendly_name: "Export Energy Abs"
        value_template: "{{ states('sensor.export_wh_accumulated')|float|abs}}"
        unit_of_measurement: Wh
        device_class: energy
        attribute_templates:
          state_class: "{{ state_attr('sensor.export_wh_accumulated', 'state_class') }}"
```

I would prefer if there had been a toggle to specify that export and energy production are negative.

Keeping value signed, allows also for simpler and neater calculations such as export+import is always consistent regardless of the size of the interval looked at or the sampling rate at which the measurements are made.
