### DISCUSSION TITLE
Template extension to parse ISO8601 duration

### DISCUSSION THREAD

**Discussion by eifinger** [home-assistant/architecture#753] [General] [answered]
I want to move my existing Alexa skill `Alexa tell Home Assistant to turn off kitchen in 10 minutes` from an Appdaemon backend to Homeassistant `intent_script`. The only thing missing is a way to convert the duration which is being parsed and provided as a slot value in the ISO8601 duration form of `PT10M` to something usable in scripts.

A possible solution could be to implement a new template `parse_duration` (or a better name) using https://github.com/gweis/isodate/ so that I can create the following script:

```yaml
intent_script:
  TurnOffInXIntent:  # Intent type
    speech:
      text: Okay
    action:
      - delay: {{ parse_duration(duration_slot) }}
      - service: light.turn_off
        target:
          entity_id: light.kitchen
```

Given I implement and test it, is this something which would be accepted as a PR?

Is there another way to solve this?

Thanks!
