### DISCUSSION TITLE
Calendar event helper

### DISCUSSION THREAD

**Discussion by allenporter** [home-assistant/architecture#776] [Entity Models]
Goals:

- Move calendar integrations away from yaml
- Improve support for more complex automations
- Improve support for displaying events

The binary sensor approach still has many gaps solved by improvements from implementation of calendar triggers, however calendar triggers alone don't solve everything.

Background & Problems:

- Google Calendar and CalDAV both implement custom ways to configure entities e.g. custom names configured in yaml and they include options like search to filter out some data within the calendar.  Search options between the two are implemented differently:
  - In CalDAV it's with matching [specific fields](https://github.com/home-assistant/core/blob/e874ba2a42d95b9312db9680023aa615f20bf542/homeassistant/components/caldav/calendar.py#L276) which is nice and simple
  - In Google Calendar, search is server side (cool!), but it sometimes has [unintuitiive behavior](https://github.com/home-assistant/core/issues/71068). Also, I'm interested in improving performance/reliability with [synchronization](https://developers.google.com/calendar/api/guides/sync) down to the device, however that doesn't work with search. Also it means every calendar (even if its search over an existing calendar) needs it's own polling, increasing API requests.
  - Moving away from yaml: For google calendar, I was trying to take the stance of not importing all yaml functionality into home assistant config flow and options flow and leaving it in yaml until we have a streamlined path.  For caldav, it's currently [proposing](https://github.com/home-assistant/core/pull/73082) adding the config flow to let you specify custom entities matching the existing yaml behavior.

- CalendarEntity has two uses and APIs:
  - Fetching a range of data, used by Rest API / Frontend, and Triggers
  - State about the next upcoming event (on or off), effectively a binary sensor but isn't one.
- The binary sensor behavior has some limitations improved by Calendar Triggers:
  - The entity polls with the default interval (often) but then the actual data fetching has a separate rate limit to only fetch data every 15 minutes.
    - This is needed to re-compute "is_offset_reached" logic, and this logic is copied between Google Calendar and Caldav.
    - This double update window behavior leads to confusion and inconsistencies e.g. why is the Frontend/Rest API updated by the next event sensor is not updated?. Why doesn't "update entity" do anything? [issue](https://github.com/home-assistant/core/issues/44145)
  - The offset logic within integrations is a hack using "!!" as a delimiter in the title, has additional limitations and potential bugs
  - It can't deal with events starting at the same time, overlapping events, any other corner case you can think of.
  - It also can't deal with multiple events that appear within the poll window.  [issue](https://github.com/home-assistant/core/issues/57128) – Integrations could theoretically deal with this by keeping an iterator around, and a backlog of events, but it's actually quite complicated to implement bug free. We don't want all integrations to implement this logic.

Calendar triggers solve all of those problems, but also currently have limitations which makes the existing binary sensors still attractive and simple for some other use cases. We have no solution for more complex automations that require conditions such as:
  - Is the event active right now? e.g. if there are multiple triggers besides the calendar event where you want both to be true. e.g. [blueprint](https://community.home-assistant.io/t/evening-light-schedule-driven-by-google-calendar/384550)
  - Is the trash picked up tomorrow? (example from Frenk)
  - Do I need my car in the next X hours? (example from Frenk)

Today all the existing conditions are very simple and stateless, and don't fetch data.  The challenge with conditions is effectively be adding a complex query in the middle of the automation.  We've discussed options such as adding an action to fetch extra trigger data, which could involve updating Service calls to return data (maybe calling a rest api bridge). I've implemented a proof of concept of having a service return data, and that works, but it still seems a bit complicated, then still requires heavy use of template logic.  Also, this doesn't really help with the use cases around displaying data based on calendar state.

Another alternative is that a user can implement some of those with template trigger binary sensors. However, we decided this is too niche or low level to include in the list of calendar automation recipes [https://www.home-assistant.io/integrations/calendar/#automation-recipes](https://github.com/home-assistant/home-assistant.io/pull/22846).  For completeness, here are some examples of how you'd do that.

Is the event active right now?
```
template:
- trigger:
   - platform: calendar
     event: start
     entity_id: calendar.device_automation_schedules
   - platform: calendar
     event: end
     entity_id: calendar.device_automation_schedules
 binary_sensor:
   - name: Calendar Backyard Light
     state: "{{ iif('#Backyard' in trigger.calendar_event.summary, iif(trigger.event == 'start', 'on', 'off'), states('binary_sensor.calendar_backyard_light')) }}"
```
 
Is trash pickup tomorrow? Today?
```
template:
- trigger:
   - platform: calendar
     event: start
     entity_id: calendar.device_automation_schedules
     offset: "-24:00:00"
   - platform: calendar
     event: end
     entity_id: calendar.device_automation_schedules
     offset: "-24:00:00"
 binary_sensor:
   - name: Trash Pickup Tomorrow
     state: "{{ iif('Trash Pickup' in trigger.calendar_event.summary, iif(trigger.event == 'start', 'on', 'off'), states('binary_sensor.trash_pickup_tomorrow')) }}"
- trigger:
   - platform: calendar
     event: start
     entity_id: calendar.device_automation_schedules
   - platform: calendar
     event: end
     entity_id: calendar.device_automation_schedules
 binary_sensor:
   - name: Trash Pickup Today
     state: "{{ iif('Trash Pickup' in trigger.calendar_event.summary, iif(trigger.event == 'start', 'on', 'off'), states('binary_sensor.trash_pickup_today')) }}"
```
 
I haven't thought through a template + trigger example for the car use case, but maybe someone with more automation experience knows how to accomplish this.

Here the templating is still quite high, however these also help with the use cases for displaying calendar data.

I lean towards adding a "Calendar Event" helper, that is effectively the equivalent to the template binary sensors which consists of optional filter criteria (search string, offsets, etc).  The calendar event helper is effectively similar to the automation UI plus extra fields for search string matching. Maybe existing yaml configuration can be imported as new helper entities.

Maybe another way to think about this is splitting the two responsibilities:
- Calendar: has fields for searching events in a date range
- Calendar Event: fetches events from the Calendar (or via trigger) then determines a state based on some filtering criteria

Happy to hear thoughts.

**Comment by bdraco** [comment]
Not sure if its helpful in brainstormign ideas, but when I think about a calendar, I think about what I want to happen before the event (what I need to do to get to the event), when the events starts, when the event ends, and after the event.

Simple use cases:
- When event starts, silence phone, turn on red light. -- the simple case would be to fire an event at this time
- When event ends, remove silent from phone, turn on green light,  -- the simple case would be to fire an event at this time

More complex cases (offset from event):
- 1 hour before event starts I want to start charging the car if its low
- 20 minute after event ends, calculate travel time to next event and send it to my phone

**Reply by allenporter** [reply]
Your examples clarifies some of the fundamentals involved, though you can implement the first three examples with calendar triggers (with or without offsets) today with templates to match on the [calendar event trigger data](https://www.home-assistant.io/docs/automation/templating/#calendar) -- but not supported with any simple search in the UI. Maybe if we narrow in on search for a moment and come back to the more complex automation cases needed for conditions.

In the first example, you might be transforming `calendar.work` into `calendar.work_from_home` based on event name or location. In the fourth example, it's hitting on a different topic,  kind of like needing something `TrackerEntity`-like for hooking up to a travel time time sensor.

Search is a condition based on the attributes of an input `CalendarEvent` ([ref](https://github.com/home-assistant/core/blob/949922ef2cb7a7c6e4a83cb91856c70728acd806/homeassistant/components/calendar/__init__.py#L78)).  Search in caldav/google today match any field (summary, description, location).

- Keep similar to today and express a single search term that matches anything.  *Aside: You really can express search using a template, but that doesn't seem very streamlined for UI (e.g. `{{ 'WFH' in calendar_event.summary OR 'WFH' in calendar_event.description OR 'WFH' in calendar_event.location }}`*

- Specify different matchers for each attribute for more control.  This could be done similar to how state attribute matching is done with a separate field name.

- Don't match on a CalendarEvent, but instead have more specific types of sensors for each attribute.  A text sensor for summary/description.  Start/end date is exposed as a `DEVICE_CLASS_DATE` as [discussed](https://github.com/home-assistant/architecture/discussions/610#discussioncomment-1196589) or `DEVICE_CLASS_TIMESTAMP`.  Something like `TrackerEntity` for event location name.   You'd still need something to turn them back into binary sensors for implementing search compatibility, but maybe using an expression reusable in conditions.

The topic of location and travel time is a lot deeper so i think we should come back to it in another discussion: Travel time integrations need a little conformity work, but do share inputs  of another entity id then try to [figure out it's location](https://github.com/home-assistant/core/blob/e67f8720e81e8618370aaf3e6a36b8b1553b9e9a/homeassistant/helpers/location.py#L48). This only accepts a lat/lng attribute or connection to a zone which calendar does not support today. As is with calendar binary sensors, it brings in all the caveats above (can't deal with events at the same time, overlapping events, etc) but maybe we ignore all of that for a moment. Related, there are opportunities  do more with event attendees and people.

**Comment by allenporter** [comment]
The post above didn't have much activity so I wanted to check back for more thoughts, but also add a little more meat in case the proposal of using a helper was lost. The basic idea is to add a calendar event helper. The calendar event helper creates an entity that matches specific events on the calendar: equivalent to the template binary sensor above, for the very common use cases supported by integrations today:

The schema can be something like:
```
calendar_event:
  trash_day:
    name: "Trash day"
    icon: "mdi:trash-can"
    entity_id: calendar.personal_calendar
    search: "Trash Day"    # Simplest version uses CalDav style matching on common attributes
```
I believe this would let us solve all of the above problems (fix limitations of the calendar binary sensor w/o templates, and have a single solution for search move away from yaml in caldav and google calendar)

Additional new functionality could include optional start/end offset matches if we want to enable conditions in automations:
```
    start_offset: "-8:00:00"   # Turn on 8 hours before
    end_offset: "00:00:00"
```
e.g. "Is trash day tomorrow?" type reminders. I'm not sure of a simple way to do more complex matching for the question "do i need my car in the next hour?" which would need more complex matches like like "location is not Home" but maybe we leave that for templates.

Critical feedback would be helpful, even if it's early.  To prime discussion with a more focused question: What is the future of yaml for these calendar integrations? Move to UI? or status quo do nothing and keep complexity of supporting UI and yaml.  (Breaking it w/o replacement isn't a choice i'm giving).
