### DISCUSSION TITLE
Add minimum brightness values to `light.turn_on` service call

### DISCUSSION THREAD

**Discussion by sarthurdev** [home-assistant/architecture#819] [Entity Models]
I'd like to propose adding `brightness_min` and `brightness_min_pct` to the `light.turn_on` service call.

The purpose of these parameters is to aid dimmer switch automations where you may not wish a stepped brightness resulting in the light switching off after decrementing equal/beyond zero.

An example switch where this is useful would be the [Hue Dimmer Switch](https://www.philips-hue.com/sv-se/p/hue-dimmer-switch/8719514274617), where there is a separate power control it seems more intuitive for the brightness controls to only affect brightness steps and not the power state.

The following example automation would step in 10% decrements, but not fall below 10%.
```
- alias: "Switch - Dim Button"
  ...
    - service: light.turn_on
      target:
        entity_id: "{{ lights }}"
      data:
        transition: 1
        brightness_step_pct: -10
        brightness_min_pct: 10
```

Relating PRs:
- https://github.com/home-assistant/core/pull/80059
- https://github.com/home-assistant/home-assistant.io/pull/24503
