### DISCUSSION TITLE
Creating automations on the fly

### DISCUSSION THREAD

**Discussion by bendikrb** [home-assistant/architecture#825] [General]
## Context

I wanted to be able to fire a TTS notifier saying, for instance, "The garbage is emptied tomorrow". However, this would be a pointless notification unless someone is around to hear it.
So, my first thought was to be able to attach a trigger to the notify platform.
Then, as I played more around with the idea - I can't see why we can't simplify this further, and at the same time make it even more powerful.

## Proposal

My proposal is to introduce a new service to the automation domain, which enables the user to effectively create one-off automations at runtime;
```yaml
- service: automation.create
  data:
    automation_id: my_random_automation_1
    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_motion_sensor
        to: 'on'
    action:
      - service: tts.google_cloud_say
        data:
          entity_id: media_player.hallway_google_speaker
          message: "The garbage will be emptied tomorrow!"
    # Optional stuff I can imagine being useful
    timeout:
      hours: 12
```

.. and perhaps a accompanying service to delete/cancel an automation;
```yaml
- service: automation.delete
  data:
    automation_id: my_random_automation_1
```

## Consequences

.. to be figured out.

**Comment by balloob** [comment]
If you're going to hard code an automation, you could just create it and disable it?

**Comment by gonzotek** [comment]
@bendikrb  
Are you proposing that an automation created with this service be ephemeral, such that after completing actions (or after the timeout) it would delete itself (vs. simply disabling, as balloob asked about).  In this particular example, I can see his point.  But I could also see potential for other use cases, e.g. what if blueprints could be used  to set up elaborate automations that might only require a couple of quick inputs from the user each time they want a 'one-shot' automation.

Simple use case: notify X, Y, & Z with message 'Q' N minutes after thing M happens (or even just after N minutes).
Given that all of the variables in this example might change quite often, I think it'd be easier to have that kind of automation self-destruct (delete itself) after it completes its actions than it would be to re-enable then edit each option (given a good interface for setting up in the first place).  One-offs/one-shots have definitely come up in the forums more than once.

**Reply by bendikrb** [reply]
> @bendikrb Are you proposing that an automation created with this service be ephemeral, such that after completing actions (or after the timeout) it would delete itself [...]

Yup, that was the idea!

**Comment by elupus** [comment]
Another use case: Any entity (light) on a dashboard screen could be asked to turn of in X minutes. Same as you could ask google assistant to turn of something in X amount time. Lightweight on the fly temporary automation.

**Reply by balloob** [reply]
Have a script with a delay that consumes a variable which is passed into the script.

**Reply by eifinger** [reply]
@elupus you can do this with a custom intent. For example I can say `Alexa tell <skill-name> to turn off Livingroom in fifteen seconds.`

The variables/slots recognized are `device`, `duration`, `onOffAction`

I pass this to a script:

```yaml
- variables:
      entity_id: >
        {% for state in states | selectattr("attributes.friendly_name",
        "defined") -%}
          {% if device==state.attributes.friendly_name -%}
            {{state.entity_id}}
          {% endif %}
        {%- endfor %}
  - delay: "{{ as_timedelta(duration) }}"
  - if:
      - condition: template
        value_template: "{{ onOffAction.startswith('off') }}"
    then:
      - service: homeassistant.turn_off
        target:
          entity_id: "{{entity_id}}"
    else:
      - service: homeassistant.turn_on
        target:
          entity_id: "{{entity_id}}"
```
Been planning for ages to write a post about this setup.
