### DISCUSSION TITLE
Action reason in history

### DISCUSSION THREAD

**Discussion by Shulyaka** [home-assistant/architecture#828] [General]
Currently the following information is available in the history (aka the Logbook panel in UI) for an entity: the time of the state change, the service used to change the state, the automation name, and the trigger that started that automation. While this is a lot of information, it is not always simple for a user to understand why the state was changed, especially in complex scenarios.
I suggest to add an additional field to hold that information: a text field containing the reason. We can add this field to the context and save it to the history. The way to set this field is a new optional field for all services. An automation or integration could pass meaningful user-friendly text explaining the reason of the action.
Example:
```
service: light.turn_on
data:
  color_temp: 400
  transition: 10
target:
  area_id: b1ce0b67b7514a56ac876ef23ad82c3a
reason: because it became dark outside
```

Before:
`Main Lights turned on triggered by automation Lights Control triggered by state of Light Sensor`
After:
`Main Lights turned on because it became dark outside`
