### DISCUSSION TITLE
Improvement to generic_hygrometer

### DISCUSSION THREAD

**Discussion by gcormier** [home-assistant/architecture#830] [General]
## Context
One of the challenges with maintaining indoor humidity in cold climates is to balance condensation on the windows. Sometimes it is not possible to achieve an ideal humidity level, as this means there will be condensation (or worst, frost) on the windows. The older (typically less efficient) the windows, the worse the issue.

Ecobee has a "frost control" setting, and other manual hygrometer controls for humidifiers will often have an external temperature sensor to take this into consideration, and they can work well. They have an unknown multiplier; Ecobee calls it "window efficiency level", which is merely a number from 1-10, and will cause Ecobee to offset the desired humidity by an unknown formula.

Where they fall short is in a large drop in temperature, such as the transition from day to night. Humidity levels will be set per the warmer daytime temperature, and once the temperature begins to drop rapidly, while the humidifier will turn off, there is still too much residual humidity in the house and condensation/frost can form.

HA has access to this information via the hourly weather forecast from the weather component. HA could also have access to an external temp sensor, be it a true sensor or the weather component's current temperature.

## Proposal
I'd like to add some optional intelligence to generic_hygrostat to

### Option 1
Modify `generic_hygromter`, 
1. Factor in a temperature sensor entity for basic "frost control"
1. Add some "look-ahead" functionality

### Option 2
Modify `generic_hygrometer` to allow `target_humidity` to reference an entity instead of a static value.
This could then be manipulated by an automation completely outside the component. `generic_hygrometer` would then merely need to ensure its aware of changes to that entity as the external logic makes changes. This would keep the changes to the component very small and perhaps impose less risk to the stability of the component for those with simple use cases. However, it would mean less "out of the box" functionality for users.

**Comment by Shulyaka** [comment]
I think that could overcomplicate the component. If you have this problem, you can have an automation adjusting the target humidity.
Something like this (use any formula you like):

```
trigger:
  - type: temperature
    platform: device
    device_id: d7ef59f5e71d48d0a0dc16928d1116bd
    entity_id: sensor.lumi_lumi_sens_04fcdbbd_temperature
    domain: sensor
  - type: temperature
    platform: device
    device_id: 1abad2e70f6f3930a45e898fdc4911cd
    entity_id: sensor.lumi_lumi_weather_95179d41_temperature
    domain: sensor
action:
  - service: humidifier.set_humidity
    data:
      humidity: "{{50 - 0.5*(states('sensor.lumi_lumi_sens_04fcdbbd_temperature') - states('sensor.lumi_lumi_weather_95179d41_temperature'))}}"
    target:
      entity_id: humidifier.my_humidifier
```
