### DISCUSSION TITLE
Error Handling in Automations

### DISCUSSION THREAD

**Discussion by depoll** [home-assistant/architecture#845] [General]
I've had trouble with the backend for one of my integrations being flaky and giving 504s (in this case Nest, but it's not the only one), which has resulted in some of my automations failing.  I'd love to be able to handle failures in my automations, but `continue_on_error` is insufficient because there's no way to determine if some step (or sequence of steps) failed and the failure was ignored (e.g. to backoff and retry).

My proposal is to add a try/catch/finally script action that would allow a user to attempt a sequence of actions in the try, handle errors (with a script variable that captures the error message and maybe the alias of the action that failed), and do cleanup work if necessary.  It would look something like:

```yaml
- try:
    - ...
  catch: #optional -- if not provided, the script still errors
    - ...
  finally: #optional -- runs regardless of errors in the catch.  Errors in this sequence are likely logged but not propagated up.
    - ...
```

Alternatively, one could add similar metadata to a script variable if a `continue_on_error` occurs, though I think the try/catch/finally is more robust (as it can handle whole sequences and doesn't get overwritten when a second error occurs).

I'm open to helping provide an implementation but wanted to first vet the proposed solution.
