### DISCUSSION TITLE
Add ` u | unit | units `  to device_class `volume`

### DISCUSSION THREAD

**Discussion by t1diotac** [home-assistant/architecture#868] [General]
Liquid measurements should include units for volumes (e.g. insulin is measured as units, or units per ml). Optionally, a separate device class of "strength" may make sense over adding unit support to volume.

Examples:
2u, 2 units, 2u/0.02ml

1u, 1 unit, 1u/0.01ml

0.2u, 0.2 units, 0.2 units/0.002ml

yaml:
```
- authentication: basic
  resource: 'http://localserver/api/v1/treatments.json?find%5Binsulin%5D%5B$gte%5D=2.5&count=1'
  sensor:
    - name: "Large Bolus Amount"
      unique_id: LargeBolusInsulinAmount
      value_template: '{{ value_json[0]["insulin"] }}'
      json_attributes:
        - "insulin"
#      device_class: "volume"
      unit_of_measurement: "units"
```
