### DISCUSSION TITLE
Add command list to Remote entity

### DISCUSSION THREAD

**Discussion by Drafteed** [home-assistant/architecture#875] [Entity Models]
## Proposal

My suggestion is to add a command list attribute to the `Remote` entity to allow integrations to store commands that can be sent by `remote.send_command` service call.

The first time I mentioned it here: https://github.com/home-assistant/core/pull/83439#issuecomment-1396892538

My suggestion is to do it like this:

```yaml
command_list:
  [keys_layout]:
    - key: Up
      command: up
    - key: Down
      command: down
      [param]: [value] # Extra send_command params for some integrations
```

With such a structure we cover two cases: 

### When the remote entity represents a virtual device in Home Assistant that sends commands to device (ATV, Bravia, Phillips, Xbox, etc.)

```yaml
command_list:
  default:
    - key: Up
      command: up
    - key: Down
      command: down
    - key: Ok
      command: confirm
```

### Remote entity can represent a physical device that sends commands (Broadlink, Harmony, another IR blaster)

```yaml
command_list:
  tv:
    - key: Up
      command: up
      device: tv
    - key: Down
      command: down
      device: tv
    - key: Ok
      command: confirm
      device: tv
  dvr:
    - key: Up
      command: up
      device: dvr
    - key: Down
      command: down
      device: dvr
    - key: Ok
      command: confirm
      device: tv
```

## Which integrations can use it:

All integrations that use `Remote` entity: https://www.home-assistant.io/integrations/#remote

## Why is it needed?

Using this data, we can build buttons in the UI (e.g. on a special card). I think this will greatly improve the user experience.

<img src="https://user-images.githubusercontent.com/11841379/218631917-49643f7b-fbbf-43da-bd39-3c9bf8887c0f.png">

<hr>

### Icon variant (in this case, we probably have to add a key containing the name of the icon):

<img src="https://user-images.githubusercontent.com/11841379/218632114-1faa93af-8f97-401d-afdd-61bc13886b17.png">
