### DISCUSSION TITLE
Namespaces for script variables

### DISCUSSION THREAD

**Discussion by depoll** [home-assistant/architecture#888] [General]
The current [script variables](https://www.home-assistant.io/docs/scripts/#variables) scoping is very limiting.  There are cases where it's helpful to build up values as branches are taken, loops iterate, etc. to then use later in the script.

Jinja has the same limitation by default -- `set` can only be used on local variables, and within loops, for example, setting the variable only applies to the inner scope.

The solution for Jinja was to add namespaces, which could be created with `set my_namespace = namespace()` and then set with `set my_namespace.variable = foo`, which essentially adds an explicit scoping mechanism.  Could we do the same?

For example:

```yaml
- namespaces:
    ns:
      var1: "{{ something }}"
- variables:
    var1: "{{ something }}" # Uses local scope
    ns.var1: "{{ something }}" # Sets the variable in the namespace
    var2: "{{ ns.var1 }}" # refers to the value of var1 in the namespace
```
