### DISCUSSION TITLE
Standardize changelog for integrations

### DISCUSSION THREAD

**Discussion by dgomes** [home-assistant/architecture#897] [General] [answered]
# Problem Statement
Whenever we have broken changes in integrations users fail to realise such and just get a bunch of errors in the logs simply because they skipped reading the breaking changes section of the release blog post.

# Solution
`manifest.json` is read before we load an integration, so we can leverage that in order to detect a broken change before it actually... breaks

I propose we update `manifest.json` to have a dict with:
```
{
  "domain": "your_domain_name",
  "name": "Your Integration",
  "documentation": "https://www.example.com",
  "dependencies": [],
  "codeowners": [],
  "requirements": [],
  "breaking_changes": {
    ha_release: "breaking change description",
  }
}
```

Upon HA upgrade, components with a breaking change trigger a persistent notification and do not actually load, giving users a chance to fix their configurations.

**Comment by awarecan** [comment]
`manifest.json` should not include change log. I propose create a separate `changelogs.md` file per integration, and not limit to breaking changes, but all changes.

I also don't like auto-disable the component, how did system know user hasn't fix the break already? In my opinion, the personalized release note should be just display the release note in a way to highlight the integration user is using. It doesn't need manifest support, the basic element already exist in current version. `system_health` component to list all using component, we just need a script to decorate release note blog base on `system_health` component list.

**Comment by balloob** [comment]
Oh I like @awarecan's idea even more. 

I suggest that if we add a changelog, we should write it in machine understandable language, so that we can automatically parse it for the release notes and show in the UI.

Preferably I want the changelog text to be in Markdown, so that we can emphasize and link important parts.

JSON sucks for Markdown, or any multiline text, so probably have a `changelog.yaml` ? I do think that we should focus on MVP, lots of possibilities, but let's focus on the bare minimum that can help us generate better release notes.

First format that comes to mind:

```yaml
domain: mqtt
changelog:
- release: 0.92
  author: "@balloob"
  breaking_change: true
  change: >
    The internal MQTT broker has been moved out of the `mqtt` integration and is now part of a new `mqtt_broker` integration. To set it up, update your configuration as follows:

    ```yaml
    mqtt_broker:
      password: bla

    mqtt:
      host: localhost
      username: homeassistant
      password: bla
    ```
```
