### DISCUSSION TITLE
Document a best practice for yaml configuration of entities

### DISCUSSION THREAD

**Discussion by emontnemery** [home-assistant/architecture#906] [General] [answered]
The structure of how entities are configured via yaml is a bit of a mixed bag.
In some cases, entities are simply listed, while in some cases the entities are instead declared as dictionaries where the keys are input for entity_id assignment.

To help both users and contributors we should document a best practice for new integrations.

I suggest that we list the various patterns in this discussion and try to agree on what pattern or patterns to document as best practice for new integrations or for integrations being refactored to be compliant with ADR 0007.

**Comment by farmio** [comment]
Another common pattern is dictionaries of lists. 

```yaml
my_integration:
  sensor:
    - name: sensor 1
      ...
    - name: sensor 2
      ...
  binary_sensor:
    - ...
``` 

There is also no consistency of singular/plural use of platform keys in all integrations (`sensor:` vs `sensors:`).

**Reply by gjohansson-ST** [reply]
I think this way makes most sense and also write it in singular so using the domain constant from each platform.

**Comment by emontnemery** [comment, marked as answer]
List of entities:

```yaml
template:
  - sensor:
      name: a sensor
      ...
  - binary_sensor:
      name: a binary sensor
      ...
  - sensor:
      name: another sensor
      ...
```

**Reply by balloob** [reply]
This is good, but let's just stick to the same format as trigger based template entities (which this more or less is).

**Reply by balloob** [reply]
The trigger based template entities config is here: https://www.home-assistant.io/integrations/template#trigger-based-template-binary-sensors-buttons-numbers-selects-and-sensors

Erik's example is a but succinct, so it should be 

```yaml
template:
  - trigger:
      - platform: time_pattern
        # This will update every night
        hours: 0
        minutes: 0
    sensor:
      # Keep track how many days have past since a date
      - name: "Not smoking"
        state: '{{ ( ( as_timestamp(now()) - as_timestamp(strptime("06.07.2018", "%d.%m.%Y")) ) / 86400 ) | round(default=0) }}'
        unit_of_measurement: "Days"
  - trigger:
      - platform: time_pattern
        # This will update every noon
        hours: 12
        minutes: 0
    binary_sensor:
      - name: "Party"
        state: '{{ ( ( now.day() in (5, 6) }}'
```

**Reply by elupus** [reply]
Im confused which format is expected here. In @balloob's example we have lists under the `sensor` key.

In @emontnemery there are lists of `sensor` keys.

```yaml
- sensor:
  name: first
- sensor:
  name: second
```

Vs

```yaml
sensor:
 - name: first
 - name: second
```

**Reply by gjohansson-ST** [reply]
I think the confusion becomes when there is shared resources or not.
I guess we should have that ADR which can also provide some examples on the differences when there is shared resources or not.

Example with shared resources (scrape)
```yaml
scrape:
  - resource: https://www.home-assistant.io
    sensor:
      - name: "Current version"
        select: ".current-version h1"
      - name: Release
        select: ".current-version h1"
        value_template: '{{ value.split(":")[1] }}'
  - resource: https://www.home-assistant.io/integrations/
    sensor:
      - name: Home Assistant impl.
        select: 'a[href="#all"]'
        value_template: '{{ value.split("(")[1].split(")")[0] }}'
```

Example when there is no shared resources or sensor etc. can only be made once (wake_on_lan https://github.com/home-assistant/core/pull/97350)

```yaml
wake_on_lan:
  - switch:
      mac: 00:01:02:03:04:05
      name: "Test WOL switch"
  - switch:
      mac: 00:01:02:03:04:06
      name: "Test WOL switch 2"
```

could make the last example look like below to make the CONFIG_SCHEMA exactly same in structure.

```yaml
wake_on_lan:
  - switch:
      - mac: 00:01:02:03:04:05
        name: "Test WOL switch"
  - switch:
      - mac: 00:01:02:03:04:06
        name: "Test WOL switch 2"
```

**Reply by elupus** [reply]
The integration could have additional non entity options too. Which make it odd being a list at the root.

```yaml
wake_on_lan:
  some_global_option: True
 - sensor: # invalid list here
```

**Reply by gjohansson-ST** [reply]
According to the decision there can not be "global options". They would have to go in the lists so sure they might get repeated but so does many other fields.

**Reply by elupus** [reply]
By decision, do you mean this accepted answer? Cause i find this here non consistent with two different formats, one suggested by balloob which does not match the one by emontnomery. Is there a discussion on global options elesewhere?

**Reply by gjohansson-ST** [reply]
Sure. But it's to set a best practice. I assume it will not fit all integrations for various reasons.
But probably it will fit most so it would be good to clarify. The only real difference between @emontnemery and @balloob 's examples are if there is a list below `sensor` or not. Otherwise structurally they are the same.

**Reply by elupus** [reply]
Yes, its rather significant difference thou :). I would consider the global integration to be the top level shared resource. So it should match scrape at resource level to remain consistent and allow sharing of parsing code.

**Reply by jbouwh** [reply]
Global options should end in the config entry instead.

**Comment by emontnemery** [comment]
Dictionary of dictionaries, the key of the inner dictionary is influencing `entity_id`:
```yaml
command_line:
  sensors:
    sensor_1:
      name: CPU Temperature
    sensor_2:
      name: Another sensor
  binary_sensors:
    binary_sensor_1:
      ...
```
