### DISCUSSION TITLE
Unified bi-directional voice assistant interface

### DISCUSSION THREAD

**Discussion by tetele** [home-assistant/architecture#907] [General]
I have not found evidence of this having been discussed in the past, so I hope this will shine some light on the future of voice assistants.

# Introduction

"Voice assistant" is a relatively loose term at the moment. These are the entities involved, as far as I understand:
- a pipeline consisting of
  - language
  - STT engine
  - intent recognition and processing engine ("conversation engine")
    - user-initiated conversation handling (what we have now)
    - server-initiated conversation handling (what we don't have, but there are some traces in the code hinting towards it)
  - TTS engine
- zero or more human-interface devices (text or audio), each making use of one or more pipelines

# Problem statement

Although the landscape is not yet complete, it would be very useful to have a unified way of connecting all of these pieces together: to be able to start a conversation (of one or more exchanges between the user and the conversation engine) from whichever side, on whichever device that is designated as a voice assistant endpoint/satellite.

These exchanges should be possible (some are today):
```
# Push to talk, user started
User (> via voice to device A, an ESP-powered speaker): "set the living room temperature to 23 degrees"
Server (> via voice on device A): "temperature set"
```

```
# Text-based conversation, user started
User (> via text to browser B): "how many lights are on?"
Server (> via text in browser B): "5"
```

```
# Follow up question in an ongoing conversation, asked by server
User (> via voice to device A): "turn on the bedroom lamp"
Server (> via voice on device A): "I cannot find anything called 'bedroom lamp' to turn on. please repeat the name of the thing you want to turn on"
User: "bedroom light"
Server: "turned on light"
```

```
# Free speech/text, spoken by user
User: "add carrots, milk and cookies to the shopping list" # note that carrots, milk and cookies are unlisted words
Server: "I've added 3 items to your shopping list. Would you like to add anything else?"
User: "coffee beans and paper towels"
Server: "I've added 2 items to your shopping list. Would you like to add anything else?"
User: "No" or keeps quiet
Server: closes conversation
```

```
# Server-initiated conversation
# Broadcast/multicast from server, followed by device-targeted conversation
Server (> voice broadcast to all voice assistant satellites that are connected to a specific pipeline): "there is a person at the front door. would you like to unlock it?"
User (> to device A): "Yes"
Server (> only to device A): "OK, door unlocked"
```

```
# Timeout for silence
Server (> voice broadcast to all voice assistant satellites that are connected to a specific pipeline): "there is a person at the front door. would you like to unlock it?"
User: doesn't say anything for X amount of time
Server: closes conversation
```

# Proposed solution

Many components would be needed to cover the use cases above:
- conversations (i.e. more than just a single query/answer) which keep track of context
- a means of signaling to HA that a device is a "voice satellite" (i.e. a device which supports bi-directional audio streaming, which is connected to HA and ready to receive input from either the user or the server), possibly related to a new `voice_assistant` domain
- a means of initiating a conversation from the server, which requires a service very similar to the `notify.notify` service
- the ability to select a "target" from which to start a conversation i.e. any of the devices which are voice assistant satellites
- all voice assistant satellites would have to be treated in the same way: phones, smart speakers, browsers etc.

Example service call:
```yaml
# server sends a message to a certain voice assistant satellite, asking the user to say something and waiting for a user voice response
# when the user responds, the server repeats what the user said
service: conversation.start
data:
  message: Say something, please
  target: voice_assistant.office
  data: platform specific
  response:
    await: true # default false
    timeout: 10s
    continue_on_timeout: false
    treat_as_intent: false # if true, the default intent engine will handle the intent
  actions: # what to do when the user responds
    - service:  conversation.continue
      conversation_id: {{ conversation_id }} # provided by the former conversation.start service call
      message: "you said {{ user_response }}
```
