### DISCUSSION TITLE
Add "blank selectors" or SubSections to blueprints

### DISCUSSION THREAD

**Discussion by jeeftor** [home-assistant/architecture#968] [Entity Models]
One of the issues I've run into on blueprints is they can become very complex.

I would like the ability to add a "section header" perhaps to blueprints so that I can group certain types of selectors together. I've done something similar to that by adding a random bool that I don't use in the image below you can see **SOUND Selection below**

<img width="537" alt="image" src="https://github.com/home-assistant/architecture/assets/6491743/18baba80-703b-4751-af27-9f2cf77a2c09">

As we've gone deeper and deeper in blueprints on the community it has become harder for people to keep track of a 20-30 selector blueprint

(I hope this is the right place to post this).

My suggestion would be something like:

```yaml
section_heading_sound:
  description: >- 
      # SOUND SELECTION
      In this section you can choose what sounds you want to play for various thing
 selector:
  empty_selector:
```

Or something like that
