### DISCUSSION TITLE
Behavior of response_variable for entity service calls

### DISCUSSION THREAD

**Discussion by eifinger** [home-assistant/architecture#991] [Entity Models] [answered]
Based on the decision on https://github.com/home-assistant/architecture/discussions/948 the following question remains:

How do we handle the script helper `response_variable`? 

For non-entity-services it can behave the same but for entity-services we need a different behavior.

# Suggestions:

Given the service response:

```yaml
light.living_room:
 some_value: 1
 some_other_value: 2
light.kitchen:
 some_value: 3
 some_other_value: 4
```

## 1. Returns a list by entity id

The response variable contains the requested variable keyed by entity id.

Service call:

```yaml
service: light.some_service
data: {}
target:
  entity_id:
    - light.living_room
    - light.kitchen
response_variable: some_value
```

Response:

```yaml
light.living_room: 1
light.kitchen: 3
```

## 2. Returns a list

The response variable contains the requested variable in a list

Service call:

```yaml
service: light.some_service
data: {}
target:
  entity_id:
    - light.living_room
    - light.kitchen
response_variable: some_value
```

Response:

```yaml
1
3
```

## 3. The entity_id can/has to be provided

The response variable contains the requested variable for the requested entity

Service call:

```yaml
service: light.some_service
data: {}
target:
  entity_id:
    - light.living_room
    - light.kitchen
response_entity: light.living_room
response_variable: some_value
```

Response:

```yaml
1
```

**Comment by allenporter** [comment, marked as answer]
My impression is that we don't need a different behavior, and the arch proposal preserves existing behavior.  The response variable for a service call is setting the entire service response with a variable with that name, not extracting a variable from the service response with that name.

So `response: some_value` should give you a variable named `some_value` with the entire dictionary response:
```
light.living_room:
 some_value: 1
 some_other_value: 2
light.kitchen:
 some_value: 3
 some_other_value: 4
```
