### ISSUE TITLE
Turning on a running script

### ISSUE THREAD

**Issue by amelchio** [home-assistant/architecture#104]
Calling `turn_on` on a script that is paused in `delay` or `wait_template` will currently short-circuit the pause and resume execution. [Source code reference](https://github.com/home-assistant/home-assistant/blob/0.82.0/homeassistant/helpers/script.py#L84-L86)

This causes confusion, see home-assistant/home-assistant#17043 for one example.

It seems that two alternatives to the current behavior are available:
1. The first invocation is aborted and the second invocation is then started.
2. We complete the delay (i.e. `turn_on` does nothing).

I don't really like either of the three options so rather than just a vote, I hope to start some discussion that might uncover other alternatives.

**Comment by armills** [comment]
I'd lean towards option 2 myself. That follows the pattern from other platforms of having no effect if the entity is already on.

I think we could also add `continue` and `restart` script services in case users want that behavior explicitly.

**Comment by balloob** [comment]
Yeah I like that. I sometimes wonder if we made a mistake of only allowing a single instance of a script running, maybe we should have a 2nd one start?

**Comment by OnFreund** [comment]
@balloob allowing several running instances of a script will also enable a generic script to turn a switch on for a given amount of time like [requested in the forums](https://community.home-assistant.io/t/generic-turn-x-on-for-y-time/86766)

**Comment by efficiosoft** [comment]
+1 for multiple instances. That would save a huge amount of boilerplate automations.

**Comment by amelchio** [comment]
How would one `turn_off` with multiple instances?

**Comment by OnFreund** [comment]
Maybe by assigning something like an instance id to each running script?

**Comment by OnFreund** [comment]
And default behavior (with no instance id passed in) would be to turn off all running instances of that script, which will preserve current behavior in case of a single running instance.

**Comment by Swamp-Ig** [comment]
So... if we allow multiple running instances of a script, we can't have a script ID or anything because services can't return anything. There's a few things you can do if the script is retriggered during a `wait_template` or a `delay`:

* `continue`: Stop waiting and continue
* `cancel`: Cancel the running script at this point
* `ignore`: Ignore the new trigger (likely the default)

You can also allow multiple instances of a script running, the default would be false to not allow this.

So here's what I'm thinking:

```yaml
example_script:
  alias: 'Example'
  allow_multiple: true
  sequence:
  - wait_template: "{{ is_state('sensor.season', 'winter') }}"
    on_restart: cancel
  - delay:
    minutes: 10
    on_restart: continue
```

How does that sound? This allows modifying what action is taken at each wait or delay point on restarting the script, and overall if multiple instances are allowed to run. You can't cancel a particular instance of a running script, but that's not really going to be something that's needed and would be very difficult to arrange given that service calls can't return data.

**Comment by Swamp-Ig** [comment]
Here's an example script that would be useful for timed off lights that turn off when there's a fan turned off. I will do this as a script, but it would more likely be an automation with a trigger on the light turning on:

```yaml
light_timer:
  allow_multiple: true
  sequence:
  - wait_template: "{{ is_state('switch.bathroom_fan', 'off') }}"
    timeout: '00:05:00'
    on_restart: cancel
  - service: light.turn_off
    data:
      entity_id: light.bathroom
```

So basically if the script gets retriggered, a new instance starts and anything waiting is cancelled. The wait finishes if the fan is turned off, or the timeout occurs.

**Comment by OnFreund** [comment]
@Swamp-Ig this is great, but it's missing one important piece - the ability for the two scripts to really run simultaneously. If I understand your suggestion correctly, you can trigger them multiple time, but eventually there's only one running instance.

Also, how do you handle the case where the wait is in a script that's being called from another script?

**Comment by Swamp-Ig** [comment]
@OnFreund when you do a service call to run a script it's called asynchronously anyhow, so if a script calls another script the first script will just carry on doing whatever it's doing without waiting for the second to finish.

>  you can trigger them multiple time, but eventually there's only one running instance.

The goal would be every script runs to completion, unless it's explicitly stopped, so yes there will be only one instance eventually, but that's a bit neither here nor there. In this scenario `script.turn_off` doesn't make a lot of sense.

I've tested what's currently happening:

Scripts just ignore further `script.turn_on` service calls, write in the log, and carry on doing whatever they're doing until they run to completion. (allow_multiple=false, on_restart=ignore). This is likely because `service.turn_off` will stop the script executing at whatever wait point it's currently on.

Automations that get re-triggered don't start again from the beginning, they will break out of whatever wait they're currently in and continue from that point. (allow_multiple=false, on_restart=continue).

**Comment by OnFreund** [comment]
@Swamp-Ig my main motivation here is actually allowing multiple running instances, so that we can, for example, have a generic `turn_on_for` script that allows you to turn something on for a given time interval. Of course, multiple instances is just one way to solve it, and a built in `turn_on_for` service might be a better option, but that's a different question.
As for the lack of need to turn scripts off, I've personally never turned a script off while it was running, so I tend to agree.

**Comment by Swamp-Ig** [comment]
Like this:

```yaml
light_timer:
  allow_multiple: true
  sequence:
  - service: light.turn_on
    data_template:
      entity_id: "{{ light_id }}"
  - delay: '00:05:00'
    on_restart: cancel
  - service: light.turn_off
    data_template:
      entity_id: "{{ light_id }}"

bathroom_on_off:
  sequence:
  - service: script.light_timer
     data:
       light_id: light.ceiling
```

Without allow_multiple this is impossible to do cleanly.

**Comment by OnFreund** [comment]
Yes, but that `on_restart: cancel` thing prevents this from having the desired behavior, unless it applies only when the same `light_id` is used. With a different parameter, it should have another running instance.

**Comment by Swamp-Ig** [comment]
Yes, it would, that's true. I had it half typed out then thought about doing the parameter. 

Probably doesn't make a lot of sense to use cancel like that for paramerised scripts. You'd have to do one script for each light.

**Comment by OnFreund** [comment]
I can actually do without cancelation, but if I understand your proposal correctly, you do require it.
As for creating a script per light/switch/etc... the problem is that I also have higher level scripts calling these, and it quickly becomes hard to maintain.

**Comment by Swamp-Ig** [comment]
This would do it, but it's not pretty:

```yaml
light_timer:
  allow_multiple: true
  sequence:
  - service: light.turn_on
    data_template:
      entity_id: "{{ light_id }}"
  - delay: '00:05:00'
  - condition: template
    value_template: "{{ (now() - state_attr(light_id, 'last_changed')) >= 300  }}"
  - service: light.turn_off
    data_template:
      entity_id: "{{ light_id }}"
```

The value template for the condition probably isn't quite correct, but you get the idea, if the last change is less than 5 mins ago, then we've got another one running and exit. It's not very clean.

Probably what you really need to do is to store the invocation parameters, and any invocation *with the same parameters* is considered a re-run. If the parameters don't match then we consider that a different invocation entirely.

**Comment by Swamp-Ig** [comment]
Shorter delay winning isn't so great. Imagine a light turned on with a motion sensor. You trigger it on for 5 mins, then trigger it again 4:50 later and it turns off after 10 seconds.

**Comment by OnFreund** [comment]
Yes, not ideal, but still better than today where you have no option of doing something like that.

**Comment by Swamp-Ig** [comment]
I think the way forward is to key uniqueness on the data passed to the script, plus add the on_restart parameters.

**Comment by OnFreund** [comment]
Just to clarify, point 3 does not apply (or is at least optional) with `allow_multiple: true`, right?

**Comment by Swamp-Ig** [comment]
Point 3 still counts, if you fire off another instance then the running ones are signaled first. If there are running instances at trigger time and allow multiple is false, the new instance doesn't run.

**Comment by balloob** [comment]
I am against automatically keyed instances. That is too much magic and is impossible to track. I much rather prefer something where we allow to pass an optional ID. That way on a per ID basis can we set options.

**Comment by OnFreund** [comment]
@Swamp-Ig in that case I might not be understanding correctly what `on_restart: ignore` means. Does that it mean ignore the new run as in don't run it, or ignore it as in continue about your business, but the new run will also continue?
If it's the former, then I think we need an additional option, which is the latter.

**Comment by Swamp-Ig** [comment]
@balloob That's a good way of doing it. The only problem would be that it would be difficult to generate a unique ID, I did think briefly of having instead of `allow_multiple` to have an `identity_template`, which defaults to a timestamp. I felt that was getting too complicated however.

@OnFreund `on_restart: ignore` would be the default option, and no action would be taken on restarting the script.

**Comment by OnFreund** [comment]
@Swamp-Ig re unique id - in any case where the parameters can be an implicit unique id you can create one by concatenating their string representations, so I'm with @balloob on this one.

As for `on_restart: ignore` the phrasing is still ambiguous. Most of my comments in this thread relied on the interpretation that `ignore` means ignore the new run as in - don't run it (ignore the trigger, if you will). Based on your most recent comments, I think when you say `ignore` you mean ignore the new run as in just let it run normally concurrently. Can you clarify?

**Comment by Swamp-Ig** [comment]
Yep that's right. Maybe no-action is better? It's the default, so can just have nothing.

**Comment by balloob** [comment]
We should not automatically create unique IDs. It's up to the service that calls the script to pass in a unique id, default to `default` so normal invocation is all on the same ID.

**Comment by Swamp-Ig** [comment]
So the default behaviour would be: `allow_multiple: true`, `on_restart: continue`. That probably makes some sense. Most of the time then the `script.turn_off` service would do nothing, or would it kill any script(s) running regardless of their `on_restart` parameter?

I'm leaning towards getting rid of `script.turn_off` completely, or at the very least not have it accessible from the UI as a switch.

**Comment by efficiosoft** [comment]
Hmm, if multiple instances can be spawned just by passing an instance id different from "default" to the script, why is a new parameter like ``allow_multiple`` then required at all?

**Comment by jazzyisj** [comment]
Found this conversation while trying to hunt down some strange behaviour with some of my wait_templates.

1.  Some of this is a little over my head but there is a lot of very good information here about how script/automations actually work, particularly with wait/delay.  Some of this should be in the docs (maybe it is and i missed haven't seen it / didn't understand?).  Would have saved me some time trying to figure a couple of things out.  The current behaviour is not what I would have expected.

2. @Swamp-Ig    I personally have a place where I turn off a script from another script.  If I have an announcement playing on the media_players and and my alarm system is triggered the alarm script turns off the announcement script so the alarm can utilize the media_players without delay.  It actually works quite well in this case for me.  I do hope after all this is hashed out we retain the ability to turn off a running script.  Not the end of the world if it turns out it can't be done though.

3.  And since some of the big hitters are in here, many thanks to you folks for your continued work on Home Assistant.  It's been a fun year or so watching it all come together!

**Comment by Swamp-Ig** [comment]
>  I do hope after all this is hashed out we retain the ability to turn off a running script. Not the end of the world if it turns out it can't be done though.

It would be a matter of figuring out what "turning off" really meant. It's not entirely clear what the semantics would actually be. You can't turn off while you're actually doing something, only during a wait state. Would turn_off mean cancel anything in a waiting state? How do you know if it's safe to cancel in that state?

You could configure it on a case by case basis, however I suspect that's going to get excessively complicated. 

Maybe for a script you do want to cancel, pass a parameter to the script, something like:

```
light_timer:
  allow_multiple: true
  sequence:
  - condition: template
    value_template: "{{ cancel == '' }}"
  - service: light.turn_on
    data_template:
      entity_id: "{{ light_id }}"
  - delay: '00:05:00'
    on_restart: cancel
  - service: light.turn_off
    data_template:
      entity_id: "{{ light_id }}"

bathroom_on_off:
  sequence:
  - service: script.light_timer
    data:
      script_id: bathroom_on_off
      light_id: light.ceiling

cancel_bathroom:
  sequence:
  - service: script.light_timer
    data:
      script_id: bathroom_on_off
      cancel: True
```

So the first script is the parameterised script to call, the second calls it with light.ceiling cancelling anything already running, and the third will invoke the script cancelling any waits and then immediately exit.
