### ISSUE TITLE
Persistent notifications and Lovelace

### ISSUE THREAD

**Issue by victorcerutti** [home-assistant/architecture#161]
I like te way the notification panel works in Lovelace as it doesn't clutter the front-end with notifications that doesn't require my direct attention.

But sometimes, I want to create a visible notification that is displayed on a particular tab or on all tabs.

Some exemples would be :
- emergency weather alert for your location
- laundry is done and hasn't been emptied
- the battery of a z-wave detector is dead…

It can already be achieved with a `conditional` card along with a `markdown` card or a custom one like I did in this exemple:
![image](https://user-images.githubusercontent.com/3236171/53335687-6b064d80-38fc-11e9-8b7d-1f6a89b7edc4.png)

But the way to configure this doesn't seem correct. Create a notification card, that is dependent of a condition, has to be manually placed on top of the others, and cannot really be dismissed.

Instead I think that improving `persistent_notification` is a solution.

The notification could be displayed on the UI with an optional argument, along with a severity code (notice, important, …) that could change its display according to the theme (yellow, green, orange, red for exemple)

What do you think ?

**Comment by victorcerutti** [comment]
![capture d ecran 2019-02-25 a 14 22 47](https://user-images.githubusercontent.com/3236171/53340304-f7b70880-3908-11e9-8f9c-5c7ba34c9f1a.jpg)

Another quick exemple for an emergency alert that could be displayed.
A proposal configuration for this alert would be:
```yaml
action:
  service: persistent_notification.create
  data:
    message: "Strong wind expected tonight between 8pm and 11pm."
    title: "Emergency alert"
    visible: true
    icon: mdi:weather-windy
    severity: emergency

```
