### ISSUE TITLE
Store core config in storage helper

### ISSUE THREAD

**Issue by balloob** [home-assistant/architecture#176]
Home Assistant has a core config that consists of:

```yaml
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 11.1111111
  longitude: 22.222222
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: UTC
```

This is currently auto-detected on launch by using an Geo IP service. These services are free and keep dying, breaking older builds and are a potential privacy issue.

I suggest:
 - We keep the YAML config
 - We drop the auto-detection of it on first boot
 - Instead of failing to boot when YAML config is omitted, we will check if core config is stored in storage
 - We allow the user to set config in storage during onboarding/via config screen
 - fire an event when core config is updated (so things like zone.home can update itself)
