### ISSUE TITLE
Allow use "for" without specifying "to" for Automation state trigger

### ISSUE THREAD

**Issue by definitio** [home-assistant/architecture#191]
I propose to allow set `for` for any state change without specifying `to` for Automation state trigger. Is there any reason to keep current restriction? It causes creating multiple automations instead one in some circumstances.

PR: https://github.com/home-assistant/home-assistant/pull/22942

**Comment by balloob** [comment]
Just specify `to: *` and it will match all?

**Comment by melyux** [comment]
@balloob That doesn't work. @definitio Any reason you closed this issue?

**Comment by definitio** [comment]
@melyux `to: "*"` works for me.

**Comment by melyux** [comment]
@definitio Really? I'm getting this error when I use an asterisk: `expected alphabetic or numeric character, but found '\n'`.

```yaml
  trigger:
  - platform: state
    entity_id:
    - sensor.upstairs_thermostat_target
    - sensor.downstairs_thermostat_target
    to: *
    for:
      seconds: 5
```

**Comment by definitio** [comment]
@melyux use quotation marks.

**Comment by melyux** [comment]
@definitio 

Thank you, that works. So it has to be `to: "*"` to work. Which is weird, it it works, but it makes no sense in this case for `for:` to require `to:` in the first place because lack of a `to:` is the same thing as `to: "*"`.

```yaml
  trigger:
  - platform: state
    entity_id:
    - sensor.upstairs_thermostat_target
    - sensor.downstairs_thermostat_target
    to: "*"
    for:
      seconds: 5
```
