### ISSUE TITLE
Change default behaviour of image_processing from periodic scan

### ISSUE THREAD

**Issue by robmarkcole** [home-assistant/architecture#216]
Currently `image_processing` components perform a `scan` at a default interval of 10 seconds. This is a bit arbitrary, and it would make more sense to do a scan when a new frame is available. Also for components which are calling a cloud service, a new user could easily rack up a bill without realising they are calling the service every 10 seconds, unless they configure a long `scan_interval`.

**Comment by balloob** [comment]
I agree. We should probably have it set to manual update only for any cloud based integration.

**Comment by i00** [comment]
How about making the scan_interval be able to be changed via script / automation ...
so the default can be set to 10,000 seconds (as [the documentation](https://www.home-assistant.io/integrations/image_processing/) states), and then upon motion, we can change it temporarily via a service automation eg:
```YAML
....
  action:
  - data:
      name: 'deepstack' #name would have to be added under the image_processing objects ... currently this is not supported
      scan_interval: 1
      for: 60 #seconds
    service: image_processing.tempalterscaninterval
```
Thanks!
