### ISSUE TITLE
Templated custom attributes for template and rest entities

### ISSUE THREAD

**Issue by Swamp-Ig** [home-assistant/architecture#220]
This was a thought prompted by home-assistant/home-assistant#23509

The components from the template and rest integrations have no or limited ability to provide templated attributes. The goal would be to allow a sensor to be configured like so:

```yaml
sensor:
  - platform: template
    sensors:
      solar_angle:
        friendly_name: "Sun angle"
        unit_of_measurement: 'degrees'
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
        attribute_templates:
          daytime: "{{ state_attr('sun.sun', 'elevation') >= 0 }}"
  - platform: rest
    name: energy usage
    resource: http://192.168.2.49/e
    attribute_templates:
      pwr: '{{value_json[0].pwr}}' 
      gas: '{{value_json[0].gas}}'
    value_template: 'value_json[0].net'
```

**Comment by Swamp-Ig** [comment]
Thinking about it some more:

The downside of this kind of approach is it breaks out from the one measurement = one entity design that the system more-or-less follows.

It may be worth considering doing something more like:

```yaml
rest_resource:
  - name: device one
    url: http://192.168.2.49/e
    method: post
```

Where you basically configure all the bits you need to call a rest interface, then have:

```yaml
sensor:
  - platform: rest
    name: energy usage net
    resource_id: device_one
    value_template: 'value_json[0].net'
  - platform: rest
    name: energy usage pwr
    resource_id: device_one
    value_template: 'value_json[0].gas'
  - platform: rest
    name: energy usage gas
    resource_id: device_one
    value_template: 'value_json[0].gas'
```

That's not to say that attributes are not (sometimes) useful, but they really exist as part of the contract of a particular domain, rather than to be just added to any entity you want.

**Comment by balloob** [comment]
The rest integration should just cache each url, so entities share the data without the user having to separate resource and template configurations.

**Comment by Swamp-Ig** [comment]
Yep, all entities using the same endpoint are one device really. The main downside of specifying in every entity though is you'd need all the data identifying the endpoint to be the same, not just the url but also including username/password/method/posted json/client cert/cookies.

What of #22664 though? Keep it or don't merge? If we keep then it should aleo apply to all template and rest components.

**Comment by balloob** [comment]
I guess if we do resources, people can specify more things like scan interval etc.

**Comment by Swamp-Ig** [comment]
Yeh exactly. There's a whole bunch of stuff you'd potentially configure for a rest endpoint, not just the URL. Even something like:

```yaml
rest:
  - name: device one
    url: http://192.168.2.49/e
    method: post
    username: joe
    password: joeisthebest
    sensors:
      - name: energy use net
        value_template: '{{ value_json[0].net }}'
    binary_sensors:
      - name: turned on
        value_template: '{{ value_json[0].net > 0.5 }}'
```

would make sense, that way you preserve the device->entity mapping that we're using elsewhere. You'd still have your typical stuff for the sensor or whatever entity, like `device_type` or whatever, but drop the custom attributes which really aren't supposed to be there in the first place according to the model we're running with. It ends up looking more like a z-wave device, or some other device.
