### ISSUE TITLE
Google assistant: secure_devices_pin use.

### ISSUE THREAD

**Issue by Swamp-Ig** [home-assistant/architecture#223]
The new code for secure_devices_pin I think needs a bit of tweaking, mostly around when it is used.

Here's what I'm thinking would be in line with the current default:

```yaml:
# Example configuration.yaml entry
google_assistant:
  project_id: YOUR_PROJECT_ID
  api_key: YOUR_API_KEY
  secured_devices:
    - domain: lock
      security: all
    - domain: cover
      device_class: 
        - door
        - garage
      security: all
```

However it would be better if security could optionally be only for "turning on" actions, like 'on', 'open', 'unlock', and not for closing actions:      

```yaml:
# Example configuration.yaml entry
google_assistant:
  project_id: YOUR_PROJECT_ID
  api_key: YOUR_API_KEY
  secured_devices:
    - domain: lock
      security: on
    - domain: cover
      device_class: 
        - door
        - garage
      security: on
```

You should also be able to override to all/on/false for particular devices:

```yaml:
# Example configuration.yaml entry
google_assistant:
  project_id: YOUR_PROJECT_ID
  api_key: YOUR_API_KEY
  entity_config:
    switch.garage_door:
      security: on
```

Happy to implement this if people are happy with the idea.

**Comment by Swamp-Ig** [comment]
Probably a good first step would be not to worry about the `secured_devices` and just allow configuration per entity.

**Comment by Swamp-Ig** [comment]
There's also an ack challenge in GA, so potentially:

```yaml
# Example configuration.yaml entry
google_assistant:
  project_id: YOUR_PROJECT_ID
  api_key: YOUR_API_KEY
  entity_config:
    switch.garage_door:
      security: on
      acknowledge: all
```

Probably it would make sense to have groups of things or large numbers of things require a group ack, I've been quite annoyed by GA sometimes turning off every light in the house when really I only wanted the bedroom off.
