### ISSUE TITLE
Change cutoff point of sun conditions to astronomical midnight

### ISSUE THREAD

**Issue by emontnemery** [home-assistant/architecture#225]
### Background:
The cutoff point for the [sun conditions](https://www.home-assistant.io/docs/scripts/conditions/#sun-condition) is midnight in local time.
This works OK in most cases, _as long as the sun sets before midnight in local time_.
In places with very skewed time zones, the sun conditions however fail.

Note: There is another issue where sun up/down events _from the wrong date_ are used when evaluating the sun conditions home-assistant/home-assistant#23664.

### Normal case
In this case, the sun sets before midnight in local time, and all is fine.
![image](https://user-images.githubusercontent.com/14281572/57397828-d35f8e00-71cd-11e9-8bbc-7676510b6a85.png)

### The problem
If the time local time is very skewed compared to astronomical time, it breaks down:
![image](https://user-images.githubusercontent.com/14281572/57397804-c5aa0880-71cd-11e9-8060-5f966c6774cc.png)
The example is similar to the summer time in Kotzebue, Alaska, which has an extremely [skewed local time zone](https://en.wikipedia.org/wiki/Time_zone#Skewing_of_zones).
In this case, "after sunset" is true from 03:00 until 23:59, which is not when the sun is down, and arguably illogical.

### Proposed change
Change cutoff point for the sun conditions to be _astronomical_ midnight instead of midnight in local time:
![image](https://user-images.githubusercontent.com/14281572/57398321-fd658000-71ce-11e9-817e-eeba503165d3.png)

**Comment by OttoWinter** [comment]
The edge-case is indeed un-intuitive.

However, I think changing it to be astronomical midnight would be un-intuitive to all 99% of other users. I don't think this will be easy to explain in the docs and the normal user will struggle to understand what is meant. This more or less boils down to what a user expects when you say "before sunrise" - at least to me the existing logic makes more sense.

Disclaimer: I don't really use the sun condition myself (mostly use elevation < 0 check). Some real-world usages of this would be interesting.

I mean, there's another interesting edge-case too: What happens when there is no sunset/sunrise? I imagine those locations with a skewed local time zone also have to deal with the "no sunset/rise" edge case - so why not have them deal with this other edge case with some templates too?

**Comment by emontnemery** [comment]
> I think changing it to be astronomical midnight would be un-intuitive to all 99% of other users. I don't think this will be easy to explain in the docs and the normal user will struggle to understand what is meant.

Yes, this is indeed a tough one! But for the 99% of the users, the local time zone is also reasonably well aligned with astronomical time, and I think it shouldn't matter if the sun conditions cutoff point is at 23.30, 00.00 or 00.00 local time.
Changing the cutoff point to astronomical midnight, also mean the conditions "work" regardless of the time zone used by home assistant.

> What happens when there is no sunset/sunrise? I imagine those locations with a skewed local time zone also have to deal with the "no sunset/rise" edge case.

You're right! If there is no sunset or sunrise, the sun conditions currently evaluate to "False", meaning any automations will anyway fail to work reliably during polar day or polar night. And as you say, the locations with a local time zone skewed enough to have sunset before sunrise local time, are very likely to experience polar day or polar night.

Maybe the right thing to do here is to not mess with the sun conditions, and instead add a warning here: https://www.home-assistant.io/docs/scripts/conditions/#sun-condition, disencouraging from using the sun-conditions and instead suggest to check for elevations?

**Comment by OttoWinter** [comment]
> I think it shouldn't matter if the sun conditions cutoff point is at 23.30, 00.00 or 00.00 local time.

Depends on the way it is used I think. Some examples of this being used in the wild would help - for me the only real thing that makes sense is checking if the sun is below or above the horizon.

**Comment by cgtobi** [comment]
Would an optional offset be a acceptable solution? So, that the user can offset the cutoff point by a reasonable amount? Or make that shift of the cutoff point to the astronomical midnight an option which defaults to `false`. That way the status quo would be conserved but for such corner cases it can be adjusted.

**Comment by emontnemery** [comment]
> for me the only real thing that makes sense is checking if the sun is below or above the horizon.

@OttoWinter Yeah, i think you're right. Hence, maybe the right thing to do is to simply update the docs to warn against using the sun conditions.

> Would an optional offset be a acceptable solution? So, that the user can offset the cutoff point by a reasonable amount? 

@cgtobi It means we expect the user to check their local time offset versus astronomical time themselves? Note that the offset changes with daylight saving time. 
If changing the cutoff point to astronomical midnight is too complicated to explain, making it user configurable must be even worse..

**Comment by emontnemery** [comment]
Some proposed documentation updates here home-assistant/home-assistant.io#9423, warning against using the sun conditons.

**Comment by OttoWinter** [comment]
I mean I would just add a new condition called `sun.below_horizon` and `sun.above_horizon` (maybe even with an `angle` property) - checking elevation attribute is fine but why not make this common task easier on users? That will certainly help with avoiding the current conditions.

**Comment by emontnemery** [comment]
@OttoWinter You don't think this is good enough?
```yaml
condition:
    condition: state  # from sunset until sunrise
    entity_id: sun.sun
    state: 'below_horizon'
```

**Comment by Swamp-Ig** [comment]
@ottowinter
There's a template sensor documented in the docs [that does this already](https://www.home-assistant.io/components/binary_sensor.template/)


```yaml
# Example configuration.yaml entry
binary_sensor:
  - platform: template
    sensors:
      sun_up:
        friendly_name: "Sun is up"
        value_template: >-
          {{ states.sun.sun.attributes.elevation|float > 0 }}
```

**Comment by emontnemery** [comment]
@Swamp-Ig I think @OttoWinter concern was this was not user friendly enough:
```yaml
condition:
    condition: state  # from sunset until sunrise
    entity_id: sun.sun
    state: 'below_horizon'
```

And it would be better to be able to do:
condition:
    condition: sun  # from sunset until sunrise
    elevation: 'below_horizon'
```

**Comment by OttoWinter** [comment]
@emontnemery Ah yes checking via state is possible too of course, didn't think of that.

Yeah my concern was that users would not use the elevation > 0 option because it involved magic templates that they might not understand. But via checking state with state condition is fine.

That being said, I would fully support adding more conditions throughout the code base. Best would be if components everywhere could register a new condition like with other registries.

**Comment by emontnemery** [comment]
>I would fully support adding more conditions throughout the code base

There was a previous attempt here:
https://github.com/home-assistant/architecture/issues/98

> Best would be if components everywhere could register a new condition like with other registries.

@OttoWinter Yes, that would be super nice, and is suggested here: home-assistant/architecture#178
I will probably have time to have a go at that in a couple of weeks, but my idea for an MVP is MQTT triggers, not sun conditions :)

**Comment by Swamp-Ig** [comment]
> I would fully support adding more conditions throughout the code base

The main ones really are `sensor.solar_elevation`, `sensor.solar_rising`, and `sensor.solar_azimuth`. 

There's a whole heap you could have, many of them derived from these three. If one was do "do it properly" you'd allow the sun device to be configured to include whatever you wanted, much like some weather components do.

Here's a pretty exhaustive list of everything I can think of:

```yaml
sun:
  monitored_conditions:
    # boolean_sensors
    - solar_day # sun is up
    - solar_rising # after solar midnight, before noon
    - solar_twilight # civil twilight
    - solar_nautical_twilight
    - solar_astronomical_twilight
    # sensors expressing degrees
    - solar_elevation
    - solar_azimuth
    - solar_zenith_angle
    - solar_right_ascension
    - solar_declination
    # enumerated state morning/afternoon/dusk/evening/early_morning/dawn
    # where dusk and dawn are civil twilight, 
    # evening is before solar midnight, and early_morning is after it
    - solar_phase
    # for the next event in degrees
    - solar_next_zenith_elevation
    - solar_next_nadir_elevation
    # sensors expressing timestamps of the next event
    - solar_next_zenith
    - solar_next_nadir
    - solar_next_sunrise
    - solar_next_sunset
    - solar_next_dusk_end # end of civil twilght
    - solar_next_dawn_begin # start of civil twilight
    - solar_next_nautical_dusk_end
    - solar_next_nautical_dawn_begin
    - solar_next_astronomical_dusk_end
    - solar_next_astronomical_dawn_begin
    # you could even have all the next_ events in last_ form too.
```

I am not of course suggesting that all of these are available, but it does become a question of how far down this particular rabbit hole does one want to go?
