### ISSUE TITLE
Template groups.

### ISSUE THREAD

**Issue by Swamp-Ig** [home-assistant/architecture#234]
Groups of entities were previously made available in the core system in order to display them on the front-end, however with Lovelace that's become less of an issue, and with areas even more so. There's still some uses for groups however, particularly when working with automations and scripts.

Currently groups are defined as a static list of entity IDs, and HA needs to get reloaded in order for them to update. This proposal explores two aspects of this: their static nature, and the way they're defined.

I've actually got the guts of all this coded up already, it's waiting in a couple of PRs and mostly just needing some reviewers to look through the code and get it merged. I don't think this will happen before the 1.0 timeline anyhow because I won't have time to finish it up.

### Groups as a template.

The first suggestion is to allow groups to be defined in different ways. I suggest a regexp match of the entity ID, a glob match, and a general template. 

Basically like it says, allow the following to work:

```yaml
group:
  all_lights:
    entities_glob: 'light.*'
  kitchen_stuff:
    entities_regexp:
      - '(light|switch)\..*kitchen.*'
```

The general template would be a template that generates a comma separated list of entity IDs:

```yaml
group:
  stuff_with_flat_batteries:
    entities_template: 
      - '{{ states.sensor
             | selectattr('attributes.battery', 'lt', 10) 
             | join(', ', attribute='entity_id') }}'
```

Clearly this last one is a pretty advanced thing, but it's the second line which is the actual guts of the operation.

We'd also allow nested groups:

```yaml
group:
  switch_stuff:
    entities: 
      - group.all_lights
      - group.all_switches
```

When expanded, these would expand out to the contents of the groups referenced (which wouldn't be auto-generated groups!)

### Handling updates

Basically the group just manages itself like a regular state, and calls `async_set` like every other entity does when the `attributes.entity_id` list changes, which then sends out a `state_changed` event.

Anything that depends on the group listens for these events, and updates accordingly.

### Defining groups

Keep this in yaml for now, however, outside the scope of this arch issue, I expect ultimately that groups would be definable in the front-end, basically by giving an ID to a front-end defined entity list. Probably we'd allow using regexp and globs to choose what appears in a particular state card, much like the monster card does.

### Using groups

There's a few spots where entity filters are used, they can be examined and modified to accept updating groups.

Areas, people, and devices are also entity groups really, the expand function should probably accept `area.kitchen` as something expandable.

It might also be a good idea maybe to get any service call that takes an entity ID to expand the IDs if they're groups and send the service call to each one.

### Implementation

With the exception of the front-end stuff, I actually have pretty much most of this coded up and in PRs ready to be reviewed. I would need the following PRs to be reviewed and accepted:

* home-assistant/home-assistant#23691 /  #193
* home-assistant/home-assistant#23590 
* follow on PR to the above that's complete and tested, but not submitted yet because it's waiting

After those three are done, the implementation of regexp matches is easy, it's just a matter of passing the regexp as a parameter to the following template:

`{{ states | regexp_match(regexp) | expand | join(', ', attribute='entity_id') }}`

Globs might need a small amount of extra work, I'd need to define a glob filter for the template engine, but that should be pretty easy with library support.

### Performance

The implementation wouldn't work out the contents of the groups every time they get queried, it would keep a list of entities matching the template and only update it whenever the entity list changed (already coded for). 

### Related issues

Drop Auto-generated groups: #177
This would replace them with something more useful.

Template function to expand groups #193 
Does much of the work. Might need to extend to expand areas, people, and devices too.
