### ISSUE TITLE
Regexp groups

### ISSUE THREAD

**Issue by Swamp-Ig** [home-assistant/architecture#235]
Much cut-down version of #234.

This would replace the existing all groups with groups defined by a regexp match on entity IDs only:

```yaml
group:
  all_lights:
    entities_regexp: 'light\..*'
  kitchen_stuff:
    entities_regexp: '(light|switch)\..*kitchen.*'
```

### Implementation

* Add key to the config.
* Register an `EVENT_STATE_CHANGED` listener in the group code
* Only react to adds or removes (new_state or old_state == `None`)
* If the entity matches the regexp add/remove it from the group
* Fire `EVENT_STATE_CHANGED` on the group to indicate the group has changed.

This is pretty lightweight and quick to both run and code up, and it doesn't depend on any other big PRs. It will replace the all_ groups as per #177, so we don't lose any functionality for those that want it.

I can almost certainly have this ready before 1.0 too, so then we don't lose any functionality for those that want it. If we do proceed with #234, then the change would be forward compatible too.
