### ISSUE TITLE
Add support for learning new commands

### ISSUE THREAD

**Issue by felipediel** [home-assistant/architecture#236]
## Context

Almost all remote control platforms must first learn the codes in order to send them. In the absence of a generic service to perform this task, remote control integrations are registering their own command learning services in a non-standard way (see Xiaomi Miio and Broadlink as examples).

## Decision

I think it would be interesting to have a generic service for this, registered inside the 'remote' component. It would be similar to the existing 'send_command' generic service, but made to perform the opposite task.

## Consequences

This would create a basis for new platforms to learn new commands using the same shared service, without having to create a new service for each platform. It would save many lines of code within the integrations and help keep things clean and organized. Since no line of code would need to be removed, there would be no instant drawbacks, but when remote control platforms adapt to the model, there may be minor changes in how to call the 'learn_command' service. Users would be able to learn new commands using the following syntax shared between different platforms:

### Example 1: Learn a single command
```yaml
- service: remote.learn_command
  data:
    entity_id: remote.bedroom
    device: television
    command: 'Turn on'
```
### Example 2: Learn a list of commands
```yaml
- service: remote.learn_command
  data:
    entity_id: remote.bedroom
    device: television
    command:
      - 'Turn on'
      - 'Turn off'
      - 'Source'
      - 'Channel up'
      - 'Channel down'
      - 'Volume up'
      - 'Volume down'
```

Today I will be creating a pull-request with the solution that I consider ideal. If it is accepted, I promise to help adapt the Broadlink platform, which is the one I use. It would be nice if someone made the same adaptation on the Xiaomi Miio platform, where I can help with the transition, but I can not test for not having the device.
