### ISSUE TITLE
Add descriptive fields to scripts and python scripts

### ISSUE THREAD

**Issue by JeffLIrion** [home-assistant/architecture#275]
## Context

In the "call services" tab, most services show a description as well as info about their parameters. It would be nice if users could provide this same info for their own scripts. 

## Proposal

Add optional fields to scripts that provide the same info that a `services.yaml` file provides. For example (the `description` and `fields` entries are new):

```yaml
script:
  tv_sleep:
    alias: 'TV: sleep'
    description: Turn off the TV after a specified length of time. 
    fields:
      seconds:
        description: The length of time to wait (in seconds).
        example: 20
    sequence:
    - delay: '00:00:{{ seconds | int }}'
    - service: media_player.turn_off
      data:
        entity_id: media_player.vizio
```

## Consequences

This will make the UI for the "call services" tab look more professional, as all the services will contain helpful descriptions.
