### ISSUE TITLE
Clean up Google Cloud

### ISSUE THREAD

**Issue by frog32** [home-assistant/architecture#318]
## Context

I am currently working on a Stackdriver Logging integration (or is logging the platform and Google Cloud the integration?) and discovered that there is at least one more integration that uses Google Cloud service account files.

A potential config would look the following (including my future Stackdriver integration):

```
tts:
  - platform: google_cloud
    key_file: googlecloud.json

google_pubsub:
  project_id: smart-home14
  topic_name: main
  credentials_json: googlecloud.json

google_stackdriver:
  key_file: googlecloud.json
  log_level: info
  project_id: smart-home14
  labels:
    source: home-assistant
```
## Proposal

Create a Google Cloud integration that as config has a service account file which I could also leverage for the Stackdriver integration. The above example would then look the following:

```
google_cloud:
  key_file: googlecloud.json

tts:
  - platform: google_cloud

google_pubsub:
  project_id: smart-home14
  topic_name: main

google_stackdriver:
  log_level: info
  labels:
    source: home-assistant
```
## Consequences

This would introduce two breaking changes but will allow for more streamlined configuration going forward.

**This does not allow for separate service accounts anymore.**
Separate service accounts only make sense if they either add security or allow better accounting. Once Home Assistant is breached it would be trivial to also extract the second service account and accounting can be done on the API level since Google Cloud bills this separately.

Any help with getting the platform and integration part right is welcome. I for example thought if stackdriver config should be part of logging in case there will be additional logging platforms in the future.

In case it is not clear from my Github profile I am actually working for Google Cloud but my job is not directly related to Home Assistant and I am mostly doing this on my own time.
