### ISSUE TITLE
Services schema

### ISSUE THREAD

**Issue by bramkragten** [home-assistant/architecture#319]
## Context

Building on top of https://github.com/home-assistant/architecture/issues/313

Our `services.yaml` files now contains information that is only useful for a user, the frontend can't work with it because we don't know what data the service expects from just a description and example.

The documentation has the same information as the `services.yaml` files, with an additional optional boolean. This information is not linked to the `service.yaml` file and is maintained separately.

## Proposal

I propose we add extra data fields to every service call attribute to define what kind of data that attribute supports.

We already do this for config flows, where the backend passes the frontend a schema of what fields it expects, this could be expanded to fit the need for all the information in service calls.

Is suggest we keep the same format as [voluptuous_serialize](https://github.com/balloob/voluptuous-serialize/blob/master/voluptuous_serialize/__init__.py) now generates so we can use the same logic to generate the UI.

This could look like this:

```yaml
turn_off:
  description: Turn a light off.
  fields:
    entity_id:
      description: Name(s) of entities to turn off.
      example: "light.kitchen"
      schema:
         required: true
         type: entity # does not exist yet
         multi: true
         limit_entity_domain: light
    transition:
      description: Duration in seconds it takes to get to next state.
      example: 60
      schema:
         required: false
         type: integer
         value_max: 90
         value_min: 0
    flash:
      description: If the light should flash. Valid values are short and long.
      example: short
      schema:
         required: false
         type: select
         options:
             - short
             - long
```

## Consequences

We can then generate the documentation from the `service.yaml` file, eliminating the need to have the same information in 2 places and thus have a single source of truth.

The frontend can start showing input fields for every service call attribute that is supported for that specific service eliminating the need to write this data in `YAML`.
