### ISSUE TITLE
Split weekday from time condition into a separate condition

### ISSUE THREAD

**Issue by Misiu** [home-assistant/architecture#356]
## Context

I'm trying to add weekday selection to the automation editor (https://github.com/home-assistant/frontend/issues/3833). I had most of the work done, but while building thinks I got feeling that time and weekdays should be split as two separate conditions.

## Proposal

I'm proposing to remove weekday from time condition and create a separate condition.
So instead:
```
condition:
  condition: time
  after: '15:00:00'
  before: '02:00:00'
  weekday:
    - mon
    - wed
    - fri
```
you will write:
```
condition:
  - condition: time
    after: '15:00:00'
    before: '02:00:00'
  - condition: weekday
    days:
      - mon
      - wed
      - fri
```
## Consequences

This will allow me to split a single complex condition into two:
![image](https://user-images.githubusercontent.com/1741838/76209305-d9653780-6201-11ea-8cc4-4964cb32b2bd.png)

to:
![image](https://user-images.githubusercontent.com/1741838/76209315-df5b1880-6201-11ea-818d-7394bffcbb0d.png)

**Comment by Misiu** [comment]
Looking at source I noticed that time condition is specified in https://github.com/home-assistant/core/blob/dev/homeassistant/helpers/condition.py#L394-L448
Any other places except `config_validation.py` and tests?

If we agree on naming I can try to hack something out.

What do you think about two options?

```
condition:
  - condition: time
    after: '15:00:00'
    before: '02:00:00'
  - condition: weekday
    days:
      - mon
      - wed
      - fri
```

or:

```
condition:
  - condition: time
    after: '15:00:00'
    before: '02:00:00'
  - condition: weekday
    mon: true
    wed: true
    fri: true
    sat: false
```

in the second example, all the days would default to `false`.

I think that to keep backward compatibility we can leave weekday as part of time condition, but mark it as deprecated and remove it in one of upcoming releases.
The new condition would work independently. This way we will have backward compatibility and new feature.

**Comment by Santobert** [comment]
Personally, I like this one:

  ```yaml
- condition: weekday
    days:
      - mon
      - wed
      - fri
```

**Comment by Misiu** [comment]
@Santobert thanks for the comment. It will be easier for me with this config :)
I'll try to hack something. As I wrote I'll create a separate condition to have backward compatibility.
Are `helpers/condition.py` the correct starting point?

**Comment by Swamp-Ig** [comment]
Just wondering, would something like:

```yaml
- condition: time
  days:
    - weekdays
```

or:

```yaml
- condition: time
  days:
    - weekend
```

or:

```yaml
- condition: time
  days:
    - mon
    - thu
```

be better?
