### ISSUE TITLE
New platform proposal: Fridge/Cooler

### ISSUE THREAD

**Issue by ajmarks** [home-assistant/architecture#430]
## Context

There is currently no entity type for fridges/freezers/coolers etc.  With more and more smart appliances on the market, this seems like an oversight.  I've been able to hackily [fake it](https://github.com/ajmarks/ha_components/blob/master/ge_kitchen/water_heater.py) using a `WaterHeaterEntity`, but that's far from ideal.

## Proposal

I think we should add a `cooler` or `fridge` platform with the ability to, at the very least, set the target temperature, monitor the current temperature and humidity (if available), control/monitor built-in ice makers and water dispensers/filters, monitor door status (open/closed), set an operation mode (normal, turbo freeze, sabbath, etc).

Honestly, the `water_heater` platform for all of its warts is pretty a solid base for this:

`WaterHeaterEntity` fridge:

![Water heater fridge](https://raw.githubusercontent.com/ajmarks/ha_components/master/img/fridge_controls_dark.png)

`state_attributes` for my hacky heater-fridge:

```yaml
min_temp: 34
max_temp: 42
operation_list:
  - Normal
  - Sabbath Mode
  - Turbo Cool
current_temperature: 32
temperature: 35
operation_mode: Normal
right_door: Closed
left_door: Closed
door_status: Closed
ice_bucket: Not Full
ice_maker: 'On'
water_filter_status: Good
friendly_name: GE Fridge
```
