### ISSUE TITLE
Support learning different command types with remote 

### ISSUE THREAD

**Issue by felipediel** [home-assistant/architecture#438]
## Context

Some devices support learning different command types, such as Broadlink RM pro and RM4 pro, which support both IR and RF commands. In such cases, it is necessary to specify the type of command that we are learning. So I made [this PR](https://github.com/home-assistant/core/pull/39670) to implement this feature by adding the `command_type` parameter to `remote.learn_command` service.

It would allow us to [add RF functionality to Broadlink's remotes](https://github.com/home-assistant/home-assistant.io/pull/14398), but it was reverted [here](https://github.com/home-assistant/core/pull/40486#issuecomment-697359525) because we haven't discussed these architectural changes before. So here I am.

## Proposal

New feature: Add the `command_type` option to `remote.learn_command` service.

## Example entry for `configuration.yaml`:

```yaml
# Example configuration.yaml
script:
  learn_tv_power_button:
    sequence:
      - service: remote.learn_command
        data:
          entity_id: remote.garage
          device: car
          command: unlock
          command_type: rf
```

## Consequences

There are no breaking changes. Broadlink is the only integration using `remote.learn_command` so far. I was the one who proposed `remote.learn_command` a year ago. This interface still needs to be improved. We would also need to have a `remote.delete_command`, I see lots of users asking for this in the community, but this is another subject.

**Comment by MartinHjelmare** [comment]
Is it not good to encode the command type in the command name?

**Comment by felipediel** [comment]
That was my initial experiment. I can make it work, but I don't like it. Here are my reasons:

### 1. Confusing
We already have the `b64:` prefix for sending. This would introduce the `ir:` and `rf:` prefix for learning. One needs to be used before the code when sending and the others before the command name when learning. And they cannot be switched. Normal people don't know how to use these things. They would simply mix up everything and think it was my fault.

### 2. Redundant
The `command_type` is the same for all commands. Having a prefix would introduce redundancy when we want to learn a list of commands.

```yaml
# Example ugly configuration.yaml
script:
  learn_tv_power_button:
    sequence:
      - service: remote.learn_command
        data:
          entity_id: remote.bedroom
          device: humidifier
          command:
            - rf:turn on
            - rf:turn off
            - rf:light on
            - rf:light off
            - rf:low
            - rf:medium
            - rf:high
```
```yaml
# Example beautiful configuration.yaml
script:
  learn_tv_power_button:
    sequence:
      - service: remote.learn_command
        data:
          entity_id: remote.bedroom
          device: humidifier
          command:
            - turn on
            - turn off
            - light on
            - light off
            - low
            - medium
            - high
          command_type: rf
```

### 3. Not intent-friendly
The idea behind remote.learn_command is being able to create interactions like:
- Alexa, ask Home Assistant to learn a command on my bedroom.
- What is the name of the device?
- TV.
- What is the type of remote?
- Infrared.
- What is the name of the command?
- Turn on.
- Ok.

If we mix commands and types things will get messy.

### 4. Complex
Having a prefix for each command can bring us situations that we would like to avoid. Let's say the user does something like this:
```yaml
# Example ugly configuration.yaml
script:
  learn_tv_power_button:
    sequence:
      - service: remote.learn_command
        data:
          entity_id: remote.bedroom
          device: humidifier
          command:
            - rf:turn on
            - ir:turn off
            - rf:light on
            - ir:light off
            - rf:low
            - ir:medium
            - rf:high
```
We can resolve this request, but it makes our logic much more complex and difficult to maintain. I think it would be better not to open this possibility, which once opened could hardly be undone without breaking changes.

The truth is that the `command_type` option is much more related to the type of remote than to the type of command itself (which derives from that). How about I rename it to `remote_type`?
