### ISSUE TITLE
Template support in matching configuration of event triggers

### ISSUE THREAD

**Issue by OnFreund** [home-assistant/architecture#466]
## Context

Following up on https://github.com/home-assistant/architecture/issues/436, I believe that having templates in the event data and context would make it significantly more powerful, especially when used with `wait_for_trigger`. 
For example, what (I believe) is a very common pattern - send an actionable notification to the app, and wait for the user to activate it - could really benefit from this (so that we only wait for the specific user that we sent the notification to).

## Proposal

I propose we add template support to event triggers. The template will have the scope of the executing script/automation, so that the `trigger` variable will be accessible, as well as any user defined variables.

## Consequences

Event triggers will become more powerful and more specific.

**Comment by balloob** [comment]
How are you going to keep track of the template changing the trigger values? Do you suggest to re-attach the trigger on every state change? What if the state change is also involved in the trigger, what then? 

Sending something to a mobile app is great, but that starts with an action, so it belongs in a script or an automation action, so it is not a trigger. `wait_for_trigger` is the right solution here, not templates in triggers.

**Comment by OnFreund** [comment]
> wait_for_trigger is the right solution here, not templates in triggers.

These are not mutually exclusive - the `wait_for_trigger` scenario is the one the benefits most from templates. Let's say an automation (with a parallel running mode) ran twice, resulting in sending two actionable notifications to two different users, and both instances are now waiting for a trigger. I believe that the current behavior would cause both instances to get out of the wait on the first user performing an action. Using templates, you'll be able to wait on a specific user in each instance.

> How are you going to keep track of the template changing the trigger values? Do you suggest to re-attach the trigger on every state change? What if the state change is also involved in the trigger, what then?

I'm not sure the trigger needs to be re-attached. It depends on what we can get from `automation_info`, and when exactly the trigger is attached.

**Comment by balloob** [comment]
Right… so you actually want to propose we support templating for `wait_for_trigger` and not all triggers everywhere in Home Assistant. That's a lot smaller scope.

How do you propose the system will know if a template is to be evaluated to generate the config for `wait_for_trigger` instead of being a template _passed_ to a trigger config?

The only thing that I can think of here is that we actually just pass the current variables to the wait_for_trigger, so any trigger that can consume templates can use it.

**Comment by OnFreund** [comment]
I think you misunderstood me. My proposal is specifically for event triggers, not all types of triggers. More specifically, it's for the use of templates in the `event_data` and `context` fields, so that you can filter an event based on runtime information, and not just static configuration.

I believe this is a way smaller scope than what you had in mind.

**Comment by OnFreund** [comment]
And if I understand https://github.com/home-assistant/core/blob/78a69ef2849baf6e0be4e34fdb9beb9bcdba98e8/homeassistant/helpers/script.py#L605 correctly, then `async_attach_trigger` is called right before the wait, which means we can evaluate the template at that point, since all the variables should have their values assigned by then.

**Comment by OnFreund** [comment]
Any thoughts after my clarification?

**Comment by OnFreund** [comment]
Trying again - any thoughts following my clarification?

**Comment by balloob** [comment]
How would it work? A config either takes templates and it is processed or it doesn't. When it does, we should also allow passing in variables.

**Comment by OnFreund** [comment]
In the same way that a value in `service` -> `data` can be either a simple value or contain templates, I'm suggesting the values in `event_data` and `context` also behave that way. If a value contains templates, they can of course include variables, and will be evaluated on the call to `async_attach_trigger`, which, if I understand correctly, is called just before the wait.

**Comment by balloob** [comment]
But templates can also be dynamic, like `{{ states.light.kitchen.state == states.input_select.hello.state }}`. That wouldn't work as the template won't be re-evaluated on each change.

**Comment by OnFreund** [comment]
You mean if the values change during the wait? That's correct, but I think we can figure out an implementation that evaluates in `handle_event` to account for that scenario.

**Comment by balloob** [comment]
Please give a YAML example how you think this should work.

**Comment by OnFreund** [comment]
This is the use case I had in mind. The automation can fire when any person arrives home, and then send an actionable notification (e.g. to turn on the light in that person's room) to that person's phone. It then waits for the specific person to take action (it has a parallel run mode so multiple instances can be active, each waiting for a different person).

```yaml
mode: parallel
trigger:
  - entity_id: person.first
    event: enter
    platform: zone
    zone: zone.home
  - entity_id: person.second
    event: enter
    platform: zone
    zone: zone.home
action:
  - variables:
      notifiers:
        person.first: notify.first
        person.second: notify.second
  - data:
      data:
        push:
          category: ...
      message: Would you like to do something?
      title: Welcome home
    service: {{ notifiers[trigger.entity_id]}}
  - wait_for_trigger:
      - variables:
          users:
            person.first: <first_user_id>
            person.second: <second_user_id>
      - platform: event
        event_type: ios.notification_action_fired
        event_data:
          categoryName: getting_home
        context:
          user_id: {{ users[trigger.entity_id] }}
```
