### ISSUE TITLE
Similar to Device Concept, Virtual/Meta/auto devices

### ISSUE THREAD

**Issue by matchett808** [home-assistant/architecture#57]
This is a bit of a ramble and a first draft/attempt, I'd like to get a feel for the response to this.

This extends on https://github.com/home-assistant/architecture/issues/36 to an extent.

**Background:**

I currently have a dumb coffee machine I made smart - this is a relatively common practice. The result of this is that I have 3 entities that constitute '1 machine' in my house (also have this for washing machine, dish washer etc). I also use the generic Climate component - which allows me to use my heating (which is a switch) with a range of temp. sensors (I actually have a custom component that averages a group - for easier management). This proposal is directly influenced by the Generic Climate Component

I'm not sure of the names of these things, but I'm proposing to add more into the set that includes:
- switch
- light
- sensor
- climate
- vacum

I'm going to refer to this group as the 'generics'

**Aim:**

Provide more 'Generics',  including ones that would replace some of the most common automations. A few ideas are:

- MotionLight/ControlledLight: Binds a light's state to that of a sensor (on/off), including exclusions for sun, time and off/on delays (don't turn off till control device has been of for 10 minutes etc)
- MotionSwitch/ControlledSwitch: same as light, but for switches, these might be able to be the 1 thing but worth splitting at this point (thinking
- ConstrainedSwitch: Devices where a number of sensors have to be 'on' in order for the 'turn on' to be proxied to the actual switch
- Doorbell: I reckon this one is obvious but a generics doorbell would be useful (note, not a video doorbell, but a device for a switch and a service to play audio that has time constraints etc).
- MultiStateSwitch (this one is a headache - but it'll come through, I promise), this would be a device that has a number of states (off, preparing, prepared, brewing, done, stale etc). The transitions would be in logical order (so off->preparing->prepared->brewing etc) with a definition of _what_ is required to trigger the state change and what is the result of the state change (service calls for simplicity). An example using my 'coffee machine' is below:

```
MultistateSwitch:
    - states:
       off:
         service: switch.turn_off
           entity_id: switch.coffee_machine_switch
       preparing:
          entity: sensor.coffee_machine_lid
          state: open
       prepared:
          entity: sensor.coffee_machine_lid
          state: closed
       brewing:
         service: switch.turn_on
           entity_id: switch.coffee_machine_switch
       ready:
          entity: sensor.coffee_machine_power
          numeric_state:
                 below: 50
      stale: 
          after:
            minutes: 30
````

**Why not just use Automations?:**

For several reasons:

- My pkg-coffeemachine.yml is about 250 lines long (in order to acheive the above). As this is an order of magnitude more terse, it stands to reason it makes it easier for the average Joe.
- As it's much more terse, this lends itself to being GUI configurable (in an easier manner) in the future.
- I have used my 'worst case scenario' on both sides here (my motion lights are only ~ 20 lines each and my idea for MotionLight/ControlledLight component the config would be a handful of lights
- it would still be possible to use automations but this makes things neater and easier to reason with - which makes things easier for us all.
- This creates devices with states and attributes that can then be used in further automations etc.

**Proposed:**

Start with the simplest. I'll create the MotionLight/ControlLight device and we can see what issues there are, what the challenges are and then if it's appropriate we can add it into core and measure how well it's received by the community before I tackle any of the more crazy ones (like MultiStateSwitch!)

**Comment by matchett808** [comment]
I'd actually also add that the important distinction between this and #36 is that this isn't for single real world devices, but it is to create virtual devices that do things (they are likely multiple different physical devices like a switch and a sensor etc).

**Comment by balloob** [comment]
We already have this concept https://developers.home-assistant.io/docs/en/architecture_components.html#components-that-respond-to-events-that-happen-within-home-assistant

**Comment by matchett808** [comment]
Yeah, sorry - my post is wirtten as though I'm proposing adding something that's fundamentally new - but actually I'm more trying to garner support to adding more of these 'components that respond to events that happen within home assistant', like I said the generic climate component was a rather large inspiration for this.

So yeah, sorry - I should really re-write this to be clearer, but I am more referring to adding new components fitting the description - my list are things that I would find useful - I suppose my post is a bit too much for a proposal  and should be broken down into singular proposals/component.

Out of interest, aside from 'components that respond to events that happen within home assistant' - is there an appropriate way to refer to these things?

So I suppose the TL:DR of the above is:

> MotionLight/ControlledLight: Binds a light's state to that of a sensor (on/off), including exclusions for sun, time and off/on delays (don't turn off till control device has been of for 10 minutes etc)

As a singular proposal to start with (I'd rather check it out here before plowing ahead and creating something that would _never_ get merged) is this a device type (domain) that would be appropriate?

As a small aside, part of the reason I've phrased my OP in the way I have is that my thinking is leaning toward all of these things being in the 1 domain (although that might be 💩 talk lol) - maybe under a banner of 'appliances' or something similar

**Comment by balloob** [comment]
A motion light is a component that fits exactly in the category I just posted. Each of such ideas should be their own component just like `device_sun_light_trigger`. They are configured by inputting existing entities and events.

**Comment by balloob** [comment]
Yes. Besides categorizing these components, we never named them. I guess a good name would be templated-automation component or something.

**Comment by Kane610** [comment]
@balloob maybe emphasise more on this together with @matchett808 integration? Might get some real power user stuff for cheap this way

**Comment by matchett808** [comment]
Yeah, they seem like 'virtual devices' or 'generics' (to hark back to the generic climate, which is what gave me the idea for the MotionLight - I started off with a temp sensor and a switch and moved to the generic climate)

> Might get some real power user stuff for cheap this way

Yeah, less power user and just lowering a barrier (it's not a huge deal for us, but I know there are folks that dread yml) to entry - MotionLights (or even ControlledLight|Switch) gets rid of a good chunk of my automations.

As things are heading toward the GUI world, then making things as simple as possible in config means that we should get to the point where _actually_ writing yml will be optional - I'd think that devices like this are going to be a big part of that (I mean, these devices aren't a 100% replacement, but if I've got 600-700 lines of yml automations that will become 75, then that's a win!)

**Comment by matchett808** [comment]
Awesome, so what I'm thinking is 
````
[name of platform]:
    light:
      targetEntity: light.light // light to turn on
      sourceEntity: sensor.motion // sensor to trigger, support for binary_sensor or sensor (eval for truthiness)
      nightimeOnly:  // Only do this at nightime, according to the constraints below
         enabled: yes
            afterSunrise: 1 hour
            beforeSunset: 1 hour 
      delayOn: 1 minute // Amount of time to wait for sensor to be on for before turing on target
      delayOff: 10 minutes // Amount of time to stay on after sensor clears

````

The above feature set for the first attempt - can then gather some opinion and update accordingly.

> templated-automation component

This is the most accurate description of what I'm really getting at here (again harking back to the generic Climate component) - sorry for the goose chase by conflating other issues and not being clear. I am essentially proposing to copy the idea of the generic climate and apply the principal to other things.

I am proposing to split this out a little and make it a first class citizen (either on the level of light/switch etc or giving light and switch etc a generic with this functionality?).

Will keep this issue open for further discussion once I've had a chance to build the thing out :)
