### ISSUE TITLE
Receive sensor data with high sample rate.

### ISSUE THREAD

**Issue by Danielhiversen** [home-assistant/architecture#63]
I am working on two different new sensors with a high sample rate (new data every 2 seconds).

And it would be interesting to show all the data in the frontend, but probably not interesting to store all these data forever.

So here are two proposals for the recorder component:

1) Add a purge_keep_days customizable per entity:
```
recorder:
  purge_interval: 10
  purge_keep_days: 10
  purge_keep_days_entity:
    days: 5
    entities:
      - sensor.my_sensor_1
      - sensor.my_sensor_2
```

This will purge sensor.my_sensor_1 and sensor.my_sensor_2 data older than 5 days, and all other data older than 10 days.
(How should we handle if you want to store 5 days of my_sensor_1 data and 3 days of my_sensor_2 data?)

2)  Add a max sample rate per entity:
```

recorder:
  purge_interval: 10
  purge_keep_days: 10
  max_sample_rate:
    seconds: 30
    entities:
      - sensor.my_sensor_1
      - sensor.my_sensor_2

```
This only store data from my_sensor_1 and my_sensor_2 every 30 seconds.
(How should we handle if you want different sample rate for my_sensor_1 data and my_sensor_2 data?)

I would prefer option 1.

Any other suggestions?

**Comment by cgarwood** [comment]
My preference would be for option 2, as I like keeping historical data. I'd be more interested in saving data for an entity once every 30 seconds forever, as opposed to saving data for an entity every 2 seconds but for only 5-10 days at a time.

**Comment by dgomes** [comment]
Here is an alternative to messing with the recorder:
- exclude that high frequency sensor from recorder
- Create a filter sensor using the THROTTLE filter

That's how I solved my very similar issue :)

**Comment by balloob** [comment]
I'm leaning towards @dgomes solution, as it keeps the recorder code simpler and it gives the user to power to decide _how_ a sensor with a fast sample size is stored. Do you just want 1 value every 30 seconds? Some people will want the average, the min or the max. They will want to put all that logic into our poor little recorder.

**Comment by Danielhiversen** [comment]
Yes, I agree that the THROTTLE filter would be fine for reducing the storing frequency.

But I think it would also be useful to specify for how long different entities should be stored in the database.
For a sensor with a high sample rate it would be useful to store all the data for plotting, but maybe only store them for 2 days.
Another case would be that most of entities you only want to store them in the database for a week. But a few entities would be useful to keep for a longer time.

In both these cases it would be useful to add a purge_keep_days customizable per entity:
```
recorder:
  purge_interval: 10
  purge_keep_days: 10
  purge_keep_days_entity:
    days: 5
    entities:
      - sensor.my_sensor_1
      - sensor.my_sensor_2
```
