### ISSUE TITLE
RFC: Wildcard support for entity_id lists

### ISSUE THREAD

**Issue by cdce8p** [home-assistant/architecture#7]
After reading about the wildcard support for `customize` and `zwave/device_config`, I thought about if something similar is possible with entity ID lists, eg. for `groups`, `history`, `recorder`, `logbook`, `service_data/entity_id`, and many other components that use them.

As an example:
```yaml
group:
  group_1:
    entities:
      - input_number.*
```

Instead of
```yaml
group:
  group_1:
    entities:
      - input_number.slider_1
      - input_number.slider_2
```

A few forum links to feature requests regarding this:
https://community.home-assistant.io/t/wildcard-operators-for-groups/4643
https://community.home-assistant.io/t/allow-wildcard-for-entity-selection-in-config-files/9029
https://community.home-assistant.io/t/wildcard-entities-in-groups/10021

As a starting point: home-assistant/home-assistant/pull/12380
Before I spend more time on it, is this something we should implement?
