### ISSUE TITLE
Creating automations on the fly

### ISSUE THREAD

**Issue by bendikrb** [home-assistant/architecture#824]
## Context

I wanted to be able to fire a TTS notifier saying, for instance, "The garbage is emptied tomorrow". However, this would be a pointless notification unless someone is around to hear it.
So, my first thought was to be able to attach a trigger to the notify platform.
Then, as I played more around with the idea - I can't see why we can't simplify this further, and at the same time make it even more powerful.

## Proposal

My proposal is to introduce a new service to the automation domain, which enables the user to effectively create one-off automations at runtime;
```yaml
- service: automation.create
  data:
    automation_id: my_random_automation_1
    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_motion_sensor
        to: 'on'
    action:
      - service: tts.google_cloud_say
        data:
          entity_id: media_player.hallway_google_speaker
          message: "The garbage will be emptied tomorrow!"
    # Optional stuff I can imagine being useful
    timeout:
      hours: 12
```

.. and perhaps a accompanying service to delete/cancel an automation;
```yaml
- service: automation.delete
  data:
    automation_id: my_random_automation_1
```

## Consequences

.. to be figured out.
